--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: .//ItemNew.xlsm

local ConsumableXls = {
    [4001] = {
        ItemID = 4001,
        ModelName = 'Trap_InHand',
        IsPutBack = false,
        UseEffectName = 'BowReleaseEffect',
        ParentNode = 'Bone_R_Hand.RHandWeaponNode',
        Offset = Vector3(0, 0.05, 0),
        Angle = EulerDegree(299, 290, 192.5),
        HealthChange = 0,
        UseAddBuffID = 0,
        UseAddBuffDur = 0.0,
        UseRemoveBuffID = 0
    },
    [4002] = {
        ItemID = 4002,
        ModelName = 'Trap_InHand',
        IsPutBack = false,
        UseEffectName = 'BowReleaseEffect',
        ParentNode = 'Bone_R_Hand.RHandWeaponNode',
        Offset = Vector3(0, 0.05, 0),
        Angle = EulerDegree(299, 290, 192.5),
        HealthChange = 0,
        UseAddBuffID = 0,
        UseAddBuffDur = 0.0,
        UseRemoveBuffID = 0
    },
    [4003] = {
        ItemID = 4003,
        ModelName = 'Trap_InHand',
        IsPutBack = false,
        UseEffectName = 'BowReleaseEffect',
        ParentNode = 'Bone_R_Hand.RHandWeaponNode',
        Offset = Vector3(0, 0.05, 0),
        Angle = EulerDegree(299, 290, 192.5),
        HealthChange = 0,
        UseAddBuffID = 0,
        UseAddBuffDur = 0.0,
        UseRemoveBuffID = 0
    },
    [4004] = {
        ItemID = 4004,
        ModelName = 'MagicEgg_InHand',
        IsPutBack = false,
        UseEffectName = 'FX_Environment_effect_16',
        ParentNode = 'Bone_R_Hand.RHandWeaponNode',
        Offset = Vector3(0, 0.05, 0),
        Angle = EulerDegree(299, 290, 192.5),
        HealthChange = 0,
        UseAddBuffID = 0,
        UseAddBuffDur = 0.0,
        UseRemoveBuffID = 0
    },
    [4005] = {
        ItemID = 4005,
        ModelName = 'item_GoStack_Black',
        IsPutBack = true,
        UseEffectName = 'FX_Environment_effect_16',
        ParentNode = 'Bone_R_Hand.RHandWeaponNode',
        Offset = Vector3(0.021, 0.0236, -0.0459),
        Angle = EulerDegree(25.6346, 45.1995, 98.461),
        HealthChange = 0,
        UseAddBuffID = 0,
        UseAddBuffDur = 0.0,
        UseRemoveBuffID = 0
    },
    [4006] = {
        ItemID = 4006,
        ModelName = 'item_GoStack_White',
        IsPutBack = true,
        UseEffectName = 'FX_Environment_effect_16',
        ParentNode = 'Bone_R_Hand.RHandWeaponNode',
        Offset = Vector3(0.021, 0.0236, -0.0459),
        Angle = EulerDegree(25.6346, 45.1995, 98.461),
        HealthChange = 0,
        UseAddBuffID = 0,
        UseAddBuffDur = 0.0,
        UseRemoveBuffID = 0
    }
}

return ConsumableXls
