--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//Item.xlsm

local UsableItemXls = {
    [3001] = {
        ItemID = 3001,
        Range = 10.0,
        HealthChange = 100,
        UseAddBuffID = 0,
        UseAddBuffDur = 0.0,
        HitAddBuffID = 0,
        HitAddBuffDur = 0.0,
        HitRemoveBuffID = 0,
        HitEffectName = 'nil',
        HitSound = '0.0',
        Hunt = false,
        Mole = true
    }
}

return UsableItemXls
