--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: .//NoticeCoinfig.xlsx

local NoticeInfoXls = {
    [1] = {
        ID = 1,
        Des = '迷宫',
        TextID = 'InfoGui_5',
        Dur = 10.0,
        ProfileImg = 'Tips_Neytiri'
    },
    [2] = {
        ID = 2,
        Des = '蜗牛即将开始',
        TextID = 'SnailGui_1',
        Dur = 10.0,
        ProfileImg = 'Tips_Manolete'
    },
    [3] = {
        ID = 3,
        Des = '蜗牛开始',
        TextID = 'SnailGui_2',
        Dur = 10.0,
        ProfileImg = 'Tips_Manolete'
    },
    [4] = {
        ID = 4,
        Des = 'UFO',
        TextID = 'InfoGui_4',
        Dur = 10.0,
        ProfileImg = 'Tips_Jake'
    }
}

return NoticeInfoXls
