--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//ItemNew.xlsx

local ClothingXls = {
    [5001] = {
        ItemID = 5001,
        UseAddBuffID = 0,
        UseAddBuffDur = 0.0,
        UseRemoveBuffID = 0,
        SkinID = 3
    }
}

return ClothingXls
