--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: .//GuitarPitch.xlsx

local ChordFretXls = {
    CMaj = {
        Chord = 'CMaj',
        StringFret = {0, 1, 0, 2, 3, 0},
        IsActive = true
    },
    Dm = {
        Chord = 'Dm',
        StringFret = {1, 3, 2, 0, 0, 0},
        IsActive = true
    },
    Em = {
        Chord = 'Em',
        StringFret = {0, 0, 0, 2, 2, 0},
        IsActive = true
    },
    FMaj = {
        Chord = 'FMaj',
        StringFret = {1, 1, 2, 3, 3, 1},
        IsActive = true
    },
    GMaj = {
        Chord = 'GMaj',
        StringFret = {3, 0, 0, 0, 2, 3},
        IsActive = true
    },
    Am = {
        Chord = 'Am',
        StringFret = {0, 1, 2, 2, 0, 0},
        IsActive = true
    }
}

return ChordFretXls
