--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: ./Design/打地鼠策划案.xlsx

local MoleGlobalConfigXls = {
    PlayerGameTime = {
        Key = 'PlayerGameTime',
        Value = 120.0
    },
    BoostNeed = {
        Key = 'BoostNeed',
        Value = 100.0
    },
    BoostTime = {
        Key = 'BoostTime',
        Value = 10.0
    },
    PlayerNumEffect = {
        Key = 'PlayerNumEffect',
        Value = {0,3,5,7,9,11,13}
    },
    RefreshTime = {
        Key = 'RefreshTime',
        Value = 6.0
    }
}

return MoleGlobalConfigXls
