--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//GameFlower.xlsx

local FlowerPointXls = {
    [1] = {
        [1] = {
            LineID = 1,
            PointID = 1,
            Pos = Vector3(1, 0, 0)
        },
        [2] = {
            LineID = 1,
            PointID = 2,
            Pos = Vector3(2, 0, 0)
        },
        [3] = {
            LineID = 1,
            PointID = 3,
            Pos = Vector3(3, 0, 0)
        },
        [4] = {
            LineID = 1,
            PointID = 4,
            Pos = Vector3(4, 0, 0)
        },
        [5] = {
            LineID = 1,
            PointID = 5,
            Pos = Vector3(5, 0, 0)
        },
        [6] = {
            LineID = 1,
            PointID = 6,
            Pos = Vector3(6, 0, 0)
        },
        [7] = {
            LineID = 1,
            PointID = 7,
            Pos = Vector3(7, 0, 0)
        },
        [8] = {
            LineID = 1,
            PointID = 8,
            Pos = Vector3(8, 0, 0)
        }
    }
}

return FlowerPointXls
