--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//Item.xlsm

local ItemXls = {
    [1001] = {
        ItemID = 1001,
        Name = 'Item_Name_1001',
        Des = 'Item_Des_1001',
        Ico = '',
        UseCD = 0.0,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [3001] = {
        ItemID = 3001,
        Name = 'Item_Name_3001',
        Des = 'Item_Des_3001',
        Ico = '',
        UseCD = 0.0,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [2001] = {
        ItemID = 2001,
        Name = 'Item_Name_2001',
        Des = 'Item_Des_2001',
        Ico = '',
        UseCD = 0.0,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [4001] = {
        ItemID = 4001,
        Name = 'Item_Name_4001',
        Des = 'Item_Des_4001',
        Ico = '',
        UseCD = 0.0,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5001] = {
        ItemID = 5001,
        Name = 'Item_Name_5001',
        Des = 'Item_Des_5001',
        Ico = '',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5002] = {
        ItemID = 5002,
        Name = 'Item_Name_5002',
        Des = 'Item_Des_5002',
        Ico = '',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5003] = {
        ItemID = 5003,
        Name = 'Item_Name_5003',
        Des = 'Item_Des_5003',
        Ico = '',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5004] = {
        ItemID = 5004,
        Name = 'Item_Name_5004',
        Des = 'Item_Des_5004',
        Ico = '',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5005] = {
        ItemID = 5005,
        Name = 'Item_Name_5005',
        Des = 'Item_Des_5005',
        Ico = '',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5006] = {
        ItemID = 5006,
        Name = 'Item_Name_5006',
        Des = 'Item_Des_5006',
        Ico = '',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5007] = {
        ItemID = 5007,
        Name = 'Item_Name_5007',
        Des = 'Item_Des_5007',
        Ico = '',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5008] = {
        ItemID = 5008,
        Name = 'Item_Name_5008',
        Des = 'Item_Des_5008',
        Ico = '',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5009] = {
        ItemID = 5009,
        Name = 'Item_Name_5009',
        Des = 'Item_Des_5009',
        Ico = '',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5010] = {
        ItemID = 5010,
        Name = 'Item_Name_5010',
        Des = 'Item_Des_5010',
        Ico = '',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5011] = {
        ItemID = 5011,
        Name = 'Item_Name_5011',
        Des = 'Item_Des_5011',
        Ico = '',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5012] = {
        ItemID = 5012,
        Name = 'Item_Name_5012',
        Des = 'Item_Des_5012',
        Ico = '',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5013] = {
        ItemID = 5013,
        Name = 'Item_Name_5013',
        Des = 'Item_Des_5013',
        Ico = '',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5014] = {
        ItemID = 5014,
        Name = 'Item_Name_5014',
        Des = 'Item_Des_5014',
        Ico = '',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5015] = {
        ItemID = 5015,
        Name = 'Item_Name_5015',
        Des = 'Item_Des_5015',
        Ico = '',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5016] = {
        ItemID = 5016,
        Name = 'Item_Name_5016',
        Des = 'Item_Des_5016',
        Ico = '',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5017] = {
        ItemID = 5017,
        Name = 'Item_Name_5017',
        Des = 'Item_Des_5017',
        Ico = '',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5018] = {
        ItemID = 5018,
        Name = 'Item_Name_5018',
        Des = 'Item_Des_5018',
        Ico = '',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5019] = {
        ItemID = 5019,
        Name = 'Item_Name_5019',
        Des = 'Item_Des_5019',
        Ico = '',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5020] = {
        ItemID = 5020,
        Name = 'Item_Name_5020',
        Des = 'Item_Des_5020',
        Ico = '',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5021] = {
        ItemID = 5021,
        Name = 'Item_Name_5021',
        Des = 'Item_Des_5021',
        Ico = '',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6001] = {
        ItemID = 6001,
        Name = 'Item_Name_6001',
        Des = 'Item_Des_6001',
        Ico = '',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    }
}

return ItemXls
