--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//Item.xlsm

local MeleeWeaponXls = {
    [1001] = {
        ItemID = 1001,
        ModelName = 'M_Sword',
        AttckCD = 2.0,
        ParentNode = 'Bone_R_Hand.RHandWeaponNode',
        Offset = Vector3(0, 0, 0),
        Angle = EulerDegree(0, 0, 0),
        HealthChange = 34,
        UseAddBuffID = 0,
        UseAddBuffDur = 0.0,
        HitAddBuffID = 0,
        HitAddBuffDur = 0.0,
        HitRemoveBuffID = 0,
        HitEffectName = 'nil',
        HitSoundID = '0.0',
        Hunt = false,
        Mole = false
    }
}

return MeleeWeaponXls
