--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//ItemNew.xlsx

local BowXls = {
    [2002] = {
        ItemID = 2002,
        ModelName = 'Arch_Wood',
        ParentNode = 'Bone_L_Hand.LHandWeaponNode',
        Offset = Vector3(0, 0, 0),
        Angle = EulerDegree(45, 0, 0),
        ChargeTime = 0.5,
        ProjectileID = 1,
        ProjectileCount = 1,
        ProjectileSpeed = 40.0,
        ChargeEffect = 'BowChangeEffect',
        ShootSoundID = 56,
        ShootEffect = 'BowReleaseEffect'
    }
}

return BowXls
