--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//GameChair.xlsx

local RideConfigXls = {
    [1] = {
        Order = 1,
        Time = 0,
        ButtonKeepTime = 4.0,
        BullSpeed = 1.0,
        QteDuration = 5.0
    },
    [2] = {
        Order = 2,
        Time = 10,
        ButtonKeepTime = 3.0,
        BullSpeed = 3.0,
        QteDuration = 4.0
    },
    [3] = {
        Order = 3,
        Time = 20,
        ButtonKeepTime = 2.0,
        BullSpeed = 5.0,
        QteDuration = 3.0
    },
    [4] = {
        Order = 4,
        Time = 30,
        ButtonKeepTime = 1.0,
        BullSpeed = 7.0,
        QteDuration = 2.0
    },
    [5] = {
        Order = 5,
        Time = 40,
        ButtonKeepTime = 0.5,
        BullSpeed = 9.0,
        QteDuration = 1.0
    }
}

return RideConfigXls
