--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//GameFlower.xlsm

local FlowerInfoXls = {
    [1] = {
        ID = 1,
        Name = '低级种子',
        Describe = '',
        Icon = '',
        Level = 1,
        Time = 10,
        Reward = nil
    },
    [2] = {
        ID = 2,
        Name = '高级种子',
        Describe = '',
        Icon = '',
        Level = 2,
        Time = 20,
        Reward = nil
    },
    [3] = {
        ID = 3,
        Name = '特级种子',
        Describe = '',
        Icon = '',
        Level = 3,
        Time = 300,
        Reward = nil
    }
}

return FlowerInfoXls
