--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//ItemConfig.xlsx

local SkinConfigXls = {
    [1] = {
        ID = 1,
        Gender = 'Male',
        Head = '奥特曼的头',
        Clothes = '奥特曼的上半身',
        Trousers = '奥特曼的腿',
        Hair = '',
        HairColor = '',
        Hands = '奥特曼的手',
        Shoes = '奥特曼的脚',
        SkinColor = '',
        HeadAccessory = '',
        FaceAccessory = '',
        BodyAccessory = '',
        Eyes = '',
        EyesColor = '',
        Brows = '',
        Nose = '',
        Mouth = '',
        Beard = '',
        FaceDecoration = ''
    }
}

return SkinConfigXls
