--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//社交岛限时竞速.xlsx

local RacePointXls = {
    [1] = {
        [1] = {
            LineId = 1,
            MaxTime = 20.0,
            PointId = 1,
            Pos = Vector3(0.7006, 0.8972, 112.6)
        },
        [2] = {
            LineId = 1,
            MaxTime = 20.0,
            PointId = 2,
            Pos = Vector3(18.8255, 0.8972, 112.83)
        },
        [3] = {
            LineId = 1,
            MaxTime = 20.0,
            PointId = 3,
            Pos = Vector3(18.9675, 0.8972, 96.8965)
        },
        [4] = {
            LineId = 1,
            MaxTime = 20.0,
            PointId = 4,
            Pos = Vector3(18.2834, 0.8972, 82.2129)
        },
        [5] = {
            LineId = 1,
            MaxTime = 20.0,
            PointId = 5,
            Pos = Vector3(-2.147, 0.8972, 81.4643)
        },
        [6] = {
            LineId = 1,
            MaxTime = 20.0,
            PointId = 6,
            Pos = Vector3(-21.9368, 0.8972, 120.19)
        }
    },
    [2] = {
        [1] = {
            LineId = 2,
            MaxTime = 15.0,
            PointId = 1,
            Pos = Vector3(-0.8655, 0.8972, 107.027)
        },
        [2] = {
            LineId = 2,
            MaxTime = 15.0,
            PointId = 2,
            Pos = Vector3(-5.2555, 0.8972, 105.15)
        },
        [3] = {
            LineId = 2,
            MaxTime = 15.0,
            PointId = 3,
            Pos = Vector3(-8.2158, 0.8972, 101.093)
        },
        [4] = {
            LineId = 2,
            MaxTime = 15.0,
            PointId = 4,
            Pos = Vector3(-8.2931, 0.8972, 95.2642)
        },
        [5] = {
            LineId = 2,
            MaxTime = 15.0,
            PointId = 5,
            Pos = Vector3(-4.3369, 0.8972, 92.546)
        },
        [6] = {
            LineId = 2,
            MaxTime = 15.0,
            PointId = 6,
            Pos = Vector3(0.3469, 0.8972, 91.4593)
        },
        [7] = {
            LineId = 2,
            MaxTime = 15.0,
            PointId = 7,
            Pos = Vector3(4.3508, 0.8972, 94.114)
        },
        [8] = {
            LineId = 2,
            MaxTime = 15.0,
            PointId = 8,
            Pos = Vector3(6.0184, 0.8972, 98.6277)
        },
        [9] = {
            LineId = 2,
            MaxTime = 15.0,
            PointId = 9,
            Pos = Vector3(6.2401, 0.8972, 101.047)
        },
        [10] = {
            LineId = 2,
            MaxTime = 15.0,
            PointId = 10,
            Pos = Vector3(5.7228, 0.8972, 104.008)
        },
        [11] = {
            LineId = 2,
            MaxTime = 15.0,
            PointId = 11,
            Pos = Vector3(3.4371, 0.8972, 106.247)
        },
        [12] = {
            LineId = 2,
            MaxTime = 15.0,
            PointId = 12,
            Pos = Vector3(0.9136, 0.8972, 108.627)
        }
    }
}

return RacePointXls
