--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: .//GameMole.xlsx

local MoleConfigXls = {
    M1 = {
        ID = 'M1',
        Archetype = 'Test1',
        Type = 'ufo',
        MoneyNum = 500,
        RewardPool = 1
    },
    M2 = {
        ID = 'M2',
        Archetype = 'Test2',
        Type = 'maze',
        MoneyNum = 500,
        RewardPool = 1
    }
}

return MoleConfigXls
