--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//GameMole.xlsx

local MoleGlobalConfigXls = {
    UFOPitNum = {
        Key = 'UFOPitNum',
        Value = 10.0
    },
    MazePitNum = {
        Key = 'MazePitNum',
        Value = 10.0
    },
    RefreshTime = {
        Key = 'RefreshTime',
        Value = 10000.0
    },
    DropCoinRange = {
        Key = 'DropCoinRange',
        Value = {{num=10,weight=10},{num=15,weight=30},{num=20,weight=30},{num=30,weight=50},{num=50,weight=30},{num=100,weight=20},{num=300,weight=10},{num=600,weight=5},{num=1000,weight=1}}
    }
}

return MoleGlobalConfigXls
