--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//InteractConfig.xlsx

local InteractXls = {
    Hunt = {
        ID = 1,
        Name = 'Hunt',
        IsEnterByNPC = false,
        RewardItemID = {}
    },
    WhackAMole = {
        ID = 2,
        Name = 'WhackAMole',
        IsEnterByNPC = true,
        RewardItemID = {}
    },
    Maze = {
        ID = 3,
        Name = 'Maze',
        IsEnterByNPC = true,
        RewardItemID = {}
    },
    Cannon = {
        ID = 4,
        Name = 'Cannon',
        IsEnterByNPC = false,
        RewardItemID = {}
    },
    Frog = {
        ID = 5,
        Name = 'Frog',
        IsEnterByNPC = true,
        RewardItemID = {}
    },
    Zeppelin = {
        ID = 6,
        Name = 'Zeppelin',
        IsEnterByNPC = false,
        RewardItemID = {}
    },
    Flower = {
        ID = 7,
        Name = 'Flower',
        IsEnterByNPC = true,
        RewardItemID = {}
    },
    Snail = {
        ID = 8,
        Name = 'Snail',
        IsEnterByNPC = true,
        RewardItemID = {}
    },
    Race = {
        ID = 9,
        Name = 'Race',
        IsEnterByNPC = true,
        RewardItemID = {}
    },
    Chair = {
        ID = 10,
        Name = 'Chair',
        IsEnterByNPC = true,
        RewardItemID = {}
    },
    MonsterArena = {
        ID = 11,
        Name = 'MonsterArena',
        IsEnterByNPC = true,
        RewardItemID = {}
    },
    NPC = {
        ID = 12,
        Name = 'NPC',
        IsEnterByNPC = true,
        RewardItemID = {}
    }
}

return InteractXls
