--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//ScenesInteractConfig.xlsx

local ScenesInteractXls = {
    [1] = {
        ID = 1,
        Name = '光剑',
        Path = 'LaserSword',
        ItemID = 1015,
        IsGet = true
    }
}

return ScenesInteractXls
