--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//ItemNew.xlsm

local TaskXls = {
    [6001] = {
        ItemID = 6001,
        TaskDes = '跟导游打个招呼吧。',
        Npc = {14},
        RewardItem = 0,
        RewardGold = 50,
        NpcText = 'Task_NpcText_6001'
    },
    [6002] = {
        ItemID = 6002,
        TaskDes = '跟安全员鲍勃了解丛林探险的注意事项。',
        Npc = {13},
        RewardItem = 0,
        RewardGold = 50,
        NpcText = 'Task_NpcText_6002'
    },
    [6003] = {
        ItemID = 6003,
        TaskDes = '跟热气球技师询问怎么乘坐热气球，他在河对岸的山上。',
        Npc = {3},
        RewardItem = 0,
        RewardGold = 50,
        NpcText = 'Task_NpcText_6003'
    },
    [6004] = {
        ItemID = 6004,
        TaskDes = '跟庆典师了解如何提升自己的魅力。',
        Npc = {5},
        RewardItem = 0,
        RewardGold = 50,
        NpcText = 'Task_NpcText_6004'
    },
    [6005] = {
        ItemID = 6005,
        TaskDes = '了解营地内的动物赛跑。',
        Npc = {6},
        RewardItem = 0,
        RewardGold = 50,
        NpcText = 'Task_NpcText_6005'
    },
    [6006] = {
        ItemID = 6006,
        TaskDes = '这个图鉴记载了有人在这片森林里发现飞碟的传说。',
        Npc = {12},
        RewardItem = 0,
        RewardGold = 200,
        NpcText = 'Task_NpcText_6006'
    },
    [6007] = {
        ItemID = 6007,
        TaskDes = '你猎杀了野猪王，去跟Zander炫耀一下吧！',
        Npc = {3},
        RewardItem = 0,
        RewardGold = 200,
        NpcText = 'Task_NpcText_6007'
    }
}

return TaskXls
