--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//GameChair.xlsx

local ChairInfoXls = {
    C1 = {
        ID = 'C1',
        Archetype = 'Chair_Normal',
        Type = 'Normal',
        Position = Vector3(-52.7432, -9.6295, -22.4228),
        Rotation = EulerDegree(0, 88.9984, 0)
    },
    C2 = {
        ID = 'C2',
        Archetype = 'Chair_Normal',
        Type = 'Normal',
        Position = Vector3(-52.7432, -9.6295, -24.8162),
        Rotation = EulerDegree(0, 88.9984, 0)
    },
    C3 = {
        ID = 'C3',
        Archetype = 'Chair_Normal',
        Type = 'Normal',
        Position = Vector3(-50.1541, -10.1058, -58.1613),
        Rotation = EulerDegree(0, 8.993, 0)
    },
    C4 = {
        ID = 'C4',
        Archetype = 'Chair_Normal',
        Type = 'Normal',
        Position = Vector3(-47.0222, -10.1058, -41.7292),
        Rotation = EulerDegree(0, -175.506, 0)
    },
    C5 = {
        ID = 'C5',
        Archetype = 'Chair_QTE',
        Type = 'QTE',
        Position = Vector3(-19.6061, -12.1366, -15.1395),
        Rotation = EulerDegree(0, 60.8302, 0)
    }
}

return ChairInfoXls
