--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: .//ItemNew.xlsm

local MaterialXls = {
    [7001] = {
        ItemID = 7001,
        MaterialType = 'Food',
        GetCoin = 5
    },
    [7002] = {
        ItemID = 7002,
        MaterialType = 'Food',
        GetCoin = 5
    },
    [7003] = {
        ItemID = 7003,
        MaterialType = 'Food',
        GetCoin = 5
    },
    [7004] = {
        ItemID = 7004,
        MaterialType = 'Food',
        GetCoin = 20
    },
    [7005] = {
        ItemID = 7005,
        MaterialType = 'Food',
        GetCoin = 10
    },
    [7006] = {
        ItemID = 7006,
        MaterialType = 'Food',
        GetCoin = 25
    },
    [7007] = {
        ItemID = 7007,
        MaterialType = 'Food',
        GetCoin = 40
    },
    [7008] = {
        ItemID = 7008,
        MaterialType = 'Food',
        GetCoin = 30
    },
    [7009] = {
        ItemID = 7009,
        MaterialType = 'Food',
        GetCoin = 5
    },
    [7010] = {
        ItemID = 7010,
        MaterialType = '',
        GetCoin = 80
    },
    [7011] = {
        ItemID = 7011,
        MaterialType = '',
        GetCoin = 70
    },
    [7012] = {
        ItemID = 7012,
        MaterialType = '',
        GetCoin = 120
    },
    [7013] = {
        ItemID = 7013,
        MaterialType = '',
        GetCoin = 50
    },
    [7014] = {
        ItemID = 7014,
        MaterialType = '',
        GetCoin = 90
    },
    [7015] = {
        ItemID = 7015,
        MaterialType = '',
        GetCoin = 160
    },
    [7016] = {
        ItemID = 7016,
        MaterialType = '',
        GetCoin = 130
    },
    [7017] = {
        ItemID = 7017,
        MaterialType = '',
        GetCoin = 240
    },
    [7018] = {
        ItemID = 7018,
        MaterialType = '',
        GetCoin = 160
    },
    [7019] = {
        ItemID = 7019,
        MaterialType = '',
        GetCoin = 130
    },
    [7020] = {
        ItemID = 7020,
        MaterialType = '',
        GetCoin = 100
    },
    [7021] = {
        ItemID = 7021,
        MaterialType = '',
        GetCoin = 5
    }
}

return MaterialXls
