--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: .//Shop.xlsx

local ShopXls = {
    [2] = {
        [2002] = {
            NpcId = 2,
            Index = 1,
            ItemId = 2002,
            Price = 1500
        },
        [2003] = {
            NpcId = 2,
            Index = 2,
            ItemId = 2003,
            Price = 2500
        },
        [2005] = {
            NpcId = 2,
            Index = 3,
            ItemId = 2005,
            Price = 10000
        },
        [4002] = {
            NpcId = 2,
            Index = 4,
            ItemId = 4002,
            Price = 300
        },
        [4003] = {
            NpcId = 2,
            Index = 5,
            ItemId = 4003,
            Price = 1000
        },
        [4004] = {
            NpcId = 2,
            Index = 6,
            ItemId = 4004,
            Price = 1500
        }
    },
    [5] = {
        [1023] = {
            NpcId = 5,
            Index = 1,
            ItemId = 1023,
            Price = 1000
        },
        [1034] = {
            NpcId = 5,
            Index = 2,
            ItemId = 1034,
            Price = 1000
        },
        [1035] = {
            NpcId = 5,
            Index = 3,
            ItemId = 1035,
            Price = 1000
        },
        [1036] = {
            NpcId = 5,
            Index = 4,
            ItemId = 1036,
            Price = 1000
        },
        [1037] = {
            NpcId = 5,
            Index = 5,
            ItemId = 1037,
            Price = 1000
        },
        [1038] = {
            NpcId = 5,
            Index = 6,
            ItemId = 1038,
            Price = 1000
        }
    },
    [10] = {
        [1013] = {
            NpcId = 10,
            Index = 1,
            ItemId = 1013,
            Price = 10000
        },
        [1014] = {
            NpcId = 10,
            Index = 2,
            ItemId = 1014,
            Price = 10000
        }
    },
    [11] = {
        [1003] = {
            NpcId = 11,
            Index = 1,
            ItemId = 1003,
            Price = 1200
        },
        [1002] = {
            NpcId = 11,
            Index = 2,
            ItemId = 1002,
            Price = 800
        },
        [1029] = {
            NpcId = 11,
            Index = 3,
            ItemId = 1029,
            Price = 1200
        },
        [1033] = {
            NpcId = 11,
            Index = 4,
            ItemId = 1033,
            Price = 800
        }
    },
    [12] = {
        [1015] = {
            NpcId = 12,
            Index = 1,
            ItemId = 1015,
            Price = 2500
        }
    }
}

return ShopXls
