--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: .//ItemNew.xlsm

local ClothingXls = {
    [5001] = {
        ItemID = 5001,
        UseAddBuffID = 0,
        UseAddBuffDur = 0.0,
        UseRemoveBuffID = 0,
        SkinID = 3
    },
    [5002] = {
        ItemID = 5002,
        UseAddBuffID = 25,
        UseAddBuffDur = -1.0,
        UseRemoveBuffID = nil,
        SkinID = 5
    },
    [5003] = {
        ItemID = 5003,
        UseAddBuffID = 0,
        UseAddBuffDur = 0.0,
        UseRemoveBuffID = 0,
        SkinID = 1
    }
}

return ClothingXls
