--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//Item.xlsm

local MedicineItemXls = {
    [2001] = {
        ItemID = 2001,
        Model = 'M_Boom',
        AnimUse = 'ThrowLowCharge',
        Range = 10.0,
        HealthChange = 100,
        UseAddBuff = nil,
        UseSound = '',
        HitSound = '',
        HitAddBuff = nil,
        HitRemoveBuff = nil,
        HitEffect = '',
        HitAnim = ''
    }
}

return MedicineItemXls
