--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//GuitarPitch.xlsx

local GuitarPitchXls = {
    [1] = {
        StringID = 1,
        Pitch = {[0]='E5',[1]='F5',[2]='F#5',[3]='G5',[4]='G#5',[5]='A5'}
    },
    [2] = {
        StringID = 2,
        Pitch = {[0]='B4',[1]='C5',[2]='C#5',[3]='D5',[4]='D#5',[5]='E5'}
    },
    [3] = {
        StringID = 3,
        Pitch = {[0]='G4',[1]='G#4',[2]='A4',[3]='A#4',[4]='B4',[5]='C5'}
    },
    [4] = {
        StringID = 4,
        Pitch = {[0]='D4',[1]='D#4',[2]='E4',[3]='F4',[4]='F#4',[5]='G4'}
    },
    [5] = {
        StringID = 5,
        Pitch = {[0]='A3',[1]='A#3',[2]='B3',[3]='C4',[4]='C#4',[5]='D4'}
    },
    [6] = {
        StringID = 6,
        Pitch = {[0]='E3',[1]='F3',[2]='F#3',[3]='G3',[4]='G#3',[5]='A3'}
    }
}

return GuitarPitchXls
