--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//Item.xlsm

local ItemXls = {
    [1001] = {
        ItemID = 1001,
        Name = 'Item_Name_1001',
        Des = 'Item_Des_1001',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1002] = {
        ItemID = 1002,
        Name = 'Item_Name_1002',
        Des = 'Item_Des_1002',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1003] = {
        ItemID = 1003,
        Name = 'Item_Name_1003',
        Des = 'Item_Des_1003',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1004] = {
        ItemID = 1004,
        Name = 'Item_Name_1004',
        Des = 'Item_Des_1004',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1005] = {
        ItemID = 1005,
        Name = 'Item_Name_1005',
        Des = 'Item_Des_1005',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1006] = {
        ItemID = 1006,
        Name = 'Item_Name_1006',
        Des = 'Item_Des_1006',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1007] = {
        ItemID = 1007,
        Name = 'Item_Name_1007',
        Des = 'Item_Des_1007',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1008] = {
        ItemID = 1008,
        Name = 'Item_Name_1008',
        Des = 'Item_Des_1008',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1009] = {
        ItemID = 1009,
        Name = 'Item_Name_1009',
        Des = 'Item_Des_1009',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1010] = {
        ItemID = 1010,
        Name = 'Item_Name_1010',
        Des = 'Item_Des_1010',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1011] = {
        ItemID = 1011,
        Name = 'Item_Name_1011',
        Des = 'Item_Des_1011',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1012] = {
        ItemID = 1012,
        Name = 'Item_Name_1012',
        Des = 'Item_Des_1012',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1013] = {
        ItemID = 1013,
        Name = 'Item_Name_1013',
        Des = 'Item_Des_1013',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1014] = {
        ItemID = 1014,
        Name = 'Item_Name_1014',
        Des = 'Item_Des_1014',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1015] = {
        ItemID = 1015,
        Name = 'Item_Name_1015',
        Des = 'Item_Des_1015',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1016] = {
        ItemID = 1016,
        Name = 'Item_Name_1016',
        Des = 'Item_Des_1016',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1017] = {
        ItemID = 1017,
        Name = 'Item_Name_1017',
        Des = 'Item_Des_1017',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1018] = {
        ItemID = 1018,
        Name = 'Item_Name_1018',
        Des = 'Item_Des_1018',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1019] = {
        ItemID = 1019,
        Name = 'Item_Name_1019',
        Des = 'Item_Des_1019',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1020] = {
        ItemID = 1020,
        Name = 'Item_Name_1020',
        Des = 'Item_Des_1020',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1021] = {
        ItemID = 1021,
        Name = 'Item_Name_1021',
        Des = 'Item_Des_1021',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1022] = {
        ItemID = 1022,
        Name = 'Item_Name_1022',
        Des = 'Item_Des_1022',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1023] = {
        ItemID = 1023,
        Name = 'Item_Name_1023',
        Des = 'Item_Des_1023',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1024] = {
        ItemID = 1024,
        Name = 'Item_Name_1024',
        Des = 'Item_Des_1024',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1025] = {
        ItemID = 1025,
        Name = 'Item_Name_1025',
        Des = 'Item_Des_1025',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1026] = {
        ItemID = 1026,
        Name = 'Item_Name_1026',
        Des = 'Item_Des_1026',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1027] = {
        ItemID = 1027,
        Name = 'Item_Name_1027',
        Des = 'Item_Des_1027',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1028] = {
        ItemID = 1028,
        Name = 'Item_Name_1028',
        Des = 'Item_Des_1028',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1029] = {
        ItemID = 1029,
        Name = 'Item_Name_1029',
        Des = 'Item_Des_1029',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1030] = {
        ItemID = 1030,
        Name = 'Item_Name_1030',
        Des = 'Item_Des_1030',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1031] = {
        ItemID = 1031,
        Name = 'Item_Name_1031',
        Des = 'Item_Des_1031',
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [1032] = {
        ItemID = 1032,
        Name = 'Item_Name_1032',
        Des = nil,
        Icon = 'MeleeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 1,
        UseAnimName = ''
    },
    [3001] = {
        ItemID = 3001,
        Name = 'Item_Name_3001',
        Des = 'Item_Des_3001',
        Icon = 'UsableItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [3002] = {
        ItemID = 3002,
        Name = 'Item_Name_3002',
        Des = 'Item_Des_3002',
        Icon = 'UsableItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [3003] = {
        ItemID = 3003,
        Name = 'Item_Name_3003',
        Des = 'Item_Des_3003',
        Icon = 'UsableItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [3004] = {
        ItemID = 3004,
        Name = 'Item_Name_3004',
        Des = 'Item_Des_3004',
        Icon = 'UsableItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [3005] = {
        ItemID = 3005,
        Name = 'Item_Name_3005',
        Des = 'Item_Des_3005',
        Icon = 'UsableItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [3006] = {
        ItemID = 3006,
        Name = 'Item_Name_3006',
        Des = 'Item_Des_3006',
        Icon = 'UsableItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [3007] = {
        ItemID = 3007,
        Name = 'Item_Name_3007',
        Des = 'Item_Des_3007',
        Icon = 'UsableItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [3008] = {
        ItemID = 3008,
        Name = 'Item_Name_3008',
        Des = 'Item_Des_3008',
        Icon = 'UsableItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [3009] = {
        ItemID = 3009,
        Name = 'Item_Name_3009',
        Des = 'Item_Des_3009',
        Icon = 'UsableItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [3010] = {
        ItemID = 3010,
        Name = 'Item_Name_3010',
        Des = 'Item_Des_3010',
        Icon = 'UsableItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [3011] = {
        ItemID = 3011,
        Name = 'Item_Name_3011',
        Des = 'Item_Des_3011',
        Icon = 'UsableItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [3012] = {
        ItemID = 3012,
        Name = 'Item_Name_3012',
        Des = 'Item_Des_3012',
        Icon = 'UsableItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [3013] = {
        ItemID = 3013,
        Name = 'Item_Name_3013',
        Des = 'Item_Des_3013',
        Icon = 'UsableItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [2001] = {
        ItemID = 2001,
        Name = 'Item_Name_2001',
        Des = 'Item_Des_2001',
        Icon = 'LongRangeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [2002] = {
        ItemID = 2002,
        Name = 'Item_Name_2002',
        Des = 'Item_Des_2002',
        Icon = 'LongRangeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [2003] = {
        ItemID = 2003,
        Name = 'Item_Name_2003',
        Des = 'Item_Des_2003',
        Icon = 'LongRangeWeapon_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [4001] = {
        ItemID = 4001,
        Name = 'Item_Name_4001',
        Des = 'Item_Des_4001',
        Icon = '',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5001] = {
        ItemID = 5001,
        Name = 'Item_Name_5001',
        Des = 'Item_Des_5001',
        Icon = 'TaskItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5002] = {
        ItemID = 5002,
        Name = 'Item_Name_5002',
        Des = 'Item_Des_5002',
        Icon = 'TaskItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5003] = {
        ItemID = 5003,
        Name = 'Item_Name_5003',
        Des = 'Item_Des_5003',
        Icon = 'TaskItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5004] = {
        ItemID = 5004,
        Name = 'Item_Name_5004',
        Des = 'Item_Des_5004',
        Icon = 'TaskItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5005] = {
        ItemID = 5005,
        Name = 'Item_Name_5005',
        Des = 'Item_Des_5005',
        Icon = 'TaskItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5006] = {
        ItemID = 5006,
        Name = 'Item_Name_5006',
        Des = 'Item_Des_5006',
        Icon = 'TaskItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5007] = {
        ItemID = 5007,
        Name = 'Item_Name_5007',
        Des = 'Item_Des_5007',
        Icon = 'TaskItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5008] = {
        ItemID = 5008,
        Name = 'Item_Name_5008',
        Des = 'Item_Des_5008',
        Icon = 'TaskItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5009] = {
        ItemID = 5009,
        Name = 'Item_Name_5009',
        Des = 'Item_Des_5009',
        Icon = 'TaskItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5010] = {
        ItemID = 5010,
        Name = 'Item_Name_5010',
        Des = 'Item_Des_5010',
        Icon = 'TaskItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5011] = {
        ItemID = 5011,
        Name = 'Item_Name_5011',
        Des = 'Item_Des_5011',
        Icon = 'TaskItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5012] = {
        ItemID = 5012,
        Name = 'Item_Name_5012',
        Des = 'Item_Des_5012',
        Icon = 'TaskItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5013] = {
        ItemID = 5013,
        Name = 'Item_Name_5013',
        Des = 'Item_Des_5013',
        Icon = 'TaskItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5014] = {
        ItemID = 5014,
        Name = 'Item_Name_5014',
        Des = 'Item_Des_5014',
        Icon = 'TaskItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5015] = {
        ItemID = 5015,
        Name = 'Item_Name_5015',
        Des = 'Item_Des_5015',
        Icon = 'TaskItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5016] = {
        ItemID = 5016,
        Name = 'Item_Name_5016',
        Des = 'Item_Des_5016',
        Icon = 'TaskItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5017] = {
        ItemID = 5017,
        Name = 'Item_Name_5017',
        Des = 'Item_Des_5017',
        Icon = 'TaskItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5018] = {
        ItemID = 5018,
        Name = 'Item_Name_5018',
        Des = 'Item_Des_5018',
        Icon = 'TaskItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5019] = {
        ItemID = 5019,
        Name = 'Item_Name_5019',
        Des = 'Item_Des_5019',
        Icon = 'TaskItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [5020] = {
        ItemID = 5020,
        Name = 'Item_Name_5020',
        Des = 'Item_Des_5020',
        Icon = 'TaskItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6001] = {
        ItemID = 6001,
        Name = 'Item_Name_6001',
        Des = 'Item_Des_6001',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6002] = {
        ItemID = 6002,
        Name = 'Item_Name_6002',
        Des = 'Item_Des_6002',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6003] = {
        ItemID = 6003,
        Name = 'Item_Name_6003',
        Des = 'Item_Des_6003',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6004] = {
        ItemID = 6004,
        Name = 'Item_Name_6004',
        Des = 'Item_Des_6004',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6005] = {
        ItemID = 6005,
        Name = 'Item_Name_6005',
        Des = 'Item_Des_6005',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6006] = {
        ItemID = 6006,
        Name = 'Item_Name_6006',
        Des = 'Item_Des_6006',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6007] = {
        ItemID = 6007,
        Name = 'Item_Name_6007',
        Des = 'Item_Des_6007',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6008] = {
        ItemID = 6008,
        Name = 'Item_Name_6008',
        Des = 'Item_Des_6008',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6009] = {
        ItemID = 6009,
        Name = 'Item_Name_6009',
        Des = 'Item_Des_6009',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6010] = {
        ItemID = 6010,
        Name = 'Item_Name_6010',
        Des = 'Item_Des_6010',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6011] = {
        ItemID = 6011,
        Name = 'Item_Name_6011',
        Des = 'Item_Des_6011',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6012] = {
        ItemID = 6012,
        Name = 'Item_Name_6012',
        Des = 'Item_Des_6012',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6013] = {
        ItemID = 6013,
        Name = 'Item_Name_6013',
        Des = 'Item_Des_6013',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6014] = {
        ItemID = 6014,
        Name = 'Item_Name_6014',
        Des = 'Item_Des_6014',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6015] = {
        ItemID = 6015,
        Name = 'Item_Name_6015',
        Des = 'Item_Des_6015',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6016] = {
        ItemID = 6016,
        Name = 'Item_Name_6016',
        Des = 'Item_Des_6016',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6017] = {
        ItemID = 6017,
        Name = 'Item_Name_6017',
        Des = 'Item_Des_6017',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6018] = {
        ItemID = 6018,
        Name = 'Item_Name_6018',
        Des = 'Item_Des_6018',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6019] = {
        ItemID = 6019,
        Name = 'Item_Name_6019',
        Des = 'Item_Des_6019',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6020] = {
        ItemID = 6020,
        Name = 'Item_Name_6020',
        Des = 'Item_Des_6020',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6021] = {
        ItemID = 6021,
        Name = 'Item_Name_6021',
        Des = 'Item_Des_6021',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6022] = {
        ItemID = 6022,
        Name = 'Item_Name_6022',
        Des = 'Item_Des_6022',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6023] = {
        ItemID = 6023,
        Name = 'Item_Name_6023',
        Des = 'Item_Des_6023',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6024] = {
        ItemID = 6024,
        Name = 'Item_Name_6024',
        Des = 'Item_Des_6024',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6025] = {
        ItemID = 6025,
        Name = 'Item_Name_6025',
        Des = 'Item_Des_6025',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6026] = {
        ItemID = 6026,
        Name = 'Item_Name_6026',
        Des = 'Item_Des_6026',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6027] = {
        ItemID = 6027,
        Name = 'Item_Name_6027',
        Des = 'Item_Des_6027',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6028] = {
        ItemID = 6028,
        Name = 'Item_Name_6028',
        Des = 'Item_Des_6028',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6029] = {
        ItemID = 6029,
        Name = 'Item_Name_6029',
        Des = 'Item_Des_6029',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6030] = {
        ItemID = 6030,
        Name = 'Item_Name_6030',
        Des = 'Item_Des_6030',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6031] = {
        ItemID = 6031,
        Name = 'Item_Name_6031',
        Des = 'Item_Des_6031',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6032] = {
        ItemID = 6032,
        Name = 'Item_Name_6032',
        Des = 'Item_Des_6032',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6033] = {
        ItemID = 6033,
        Name = 'Item_Name_6033',
        Des = 'Item_Des_6033',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6034] = {
        ItemID = 6034,
        Name = 'Item_Name_6034',
        Des = 'Item_Des_6034',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6035] = {
        ItemID = 6035,
        Name = 'Item_Name_6035',
        Des = 'Item_Des_6035',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6036] = {
        ItemID = 6036,
        Name = 'Item_Name_6036',
        Des = 'Item_Des_6036',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6037] = {
        ItemID = 6037,
        Name = 'Item_Name_6037',
        Des = 'Item_Des_6037',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6038] = {
        ItemID = 6038,
        Name = 'Item_Name_6038',
        Des = 'Item_Des_6038',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6039] = {
        ItemID = 6039,
        Name = 'Item_Name_6039',
        Des = 'Item_Des_6039',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6040] = {
        ItemID = 6040,
        Name = 'Item_Name_6040',
        Des = 'Item_Des_6040',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6041] = {
        ItemID = 6041,
        Name = 'Item_Name_6041',
        Des = 'Item_Des_6041',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6042] = {
        ItemID = 6042,
        Name = 'Item_Name_6042',
        Des = 'Item_Des_6042',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6043] = {
        ItemID = 6043,
        Name = 'Item_Name_6043',
        Des = 'Item_Des_6043',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6044] = {
        ItemID = 6044,
        Name = 'Item_Name_6044',
        Des = 'Item_Des_6044',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6045] = {
        ItemID = 6045,
        Name = 'Item_Name_6045',
        Des = 'Item_Des_6045',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6046] = {
        ItemID = 6046,
        Name = 'Item_Name_6046',
        Des = 'Item_Des_6046',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6047] = {
        ItemID = 6047,
        Name = 'Item_Name_6047',
        Des = 'Item_Des_6047',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6048] = {
        ItemID = 6048,
        Name = 'Item_Name_6048',
        Des = 'Item_Des_6048',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6049] = {
        ItemID = 6049,
        Name = 'Item_Name_6049',
        Des = 'Item_Des_6049',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6050] = {
        ItemID = 6050,
        Name = 'Item_Name_6050',
        Des = 'Item_Des_6050',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6051] = {
        ItemID = 6051,
        Name = 'Item_Name_6051',
        Des = 'Item_Des_6051',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6052] = {
        ItemID = 6052,
        Name = 'Item_Name_6052',
        Des = 'Item_Des_6052',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6053] = {
        ItemID = 6053,
        Name = 'Item_Name_6053',
        Des = 'Item_Des_6053',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6054] = {
        ItemID = 6054,
        Name = 'Item_Name_6054',
        Des = 'Item_Des_6054',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6055] = {
        ItemID = 6055,
        Name = 'Item_Name_6055',
        Des = 'Item_Des_6055',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6056] = {
        ItemID = 6056,
        Name = 'Item_Name_6056',
        Des = 'Item_Des_6056',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6057] = {
        ItemID = 6057,
        Name = 'Item_Name_6057',
        Des = 'Item_Des_6057',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6058] = {
        ItemID = 6058,
        Name = 'Item_Name_6058',
        Des = 'Item_Des_6058',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6059] = {
        ItemID = 6059,
        Name = 'Item_Name_6059',
        Des = 'Item_Des_6059',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6060] = {
        ItemID = 6060,
        Name = 'Item_Name_6060',
        Des = 'Item_Des_6060',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6061] = {
        ItemID = 6061,
        Name = 'Item_Name_6061',
        Des = 'Item_Des_6061',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6062] = {
        ItemID = 6062,
        Name = 'Item_Name_6062',
        Des = 'Item_Des_6062',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6063] = {
        ItemID = 6063,
        Name = 'Item_Name_6063',
        Des = 'Item_Des_6063',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6064] = {
        ItemID = 6064,
        Name = 'Item_Name_6064',
        Des = 'Item_Des_6064',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6065] = {
        ItemID = 6065,
        Name = 'Item_Name_6065',
        Des = 'Item_Des_6065',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6066] = {
        ItemID = 6066,
        Name = 'Item_Name_6066',
        Des = 'Item_Des_6066',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6067] = {
        ItemID = 6067,
        Name = 'Item_Name_6067',
        Des = 'Item_Des_6067',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6068] = {
        ItemID = 6068,
        Name = 'Item_Name_6068',
        Des = 'Item_Des_6068',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6069] = {
        ItemID = 6069,
        Name = 'Item_Name_6069',
        Des = 'Item_Des_6069',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6070] = {
        ItemID = 6070,
        Name = 'Item_Name_6070',
        Des = 'Item_Des_6070',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6071] = {
        ItemID = 6071,
        Name = 'Item_Name_6071',
        Des = 'Item_Des_6071',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6072] = {
        ItemID = 6072,
        Name = 'Item_Name_6072',
        Des = 'Item_Des_6072',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6073] = {
        ItemID = 6073,
        Name = 'Item_Name_6073',
        Des = 'Item_Des_6073',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6074] = {
        ItemID = 6074,
        Name = 'Item_Name_6074',
        Des = 'Item_Des_6074',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6075] = {
        ItemID = 6075,
        Name = 'Item_Name_6075',
        Des = 'Item_Des_6075',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6076] = {
        ItemID = 6076,
        Name = 'Item_Name_6076',
        Des = 'Item_Des_6076',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6077] = {
        ItemID = 6077,
        Name = 'Item_Name_6077',
        Des = 'Item_Des_6077',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6078] = {
        ItemID = 6078,
        Name = 'Item_Name_6078',
        Des = 'Item_Des_6078',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6079] = {
        ItemID = 6079,
        Name = 'Item_Name_6079',
        Des = 'Item_Des_6079',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6080] = {
        ItemID = 6080,
        Name = 'Item_Name_6080',
        Des = 'Item_Des_6080',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6081] = {
        ItemID = 6081,
        Name = 'Item_Name_6081',
        Des = 'Item_Des_6081',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6082] = {
        ItemID = 6082,
        Name = 'Item_Name_6082',
        Des = 'Item_Des_6082',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6083] = {
        ItemID = 6083,
        Name = 'Item_Name_6083',
        Des = 'Item_Des_6083',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6084] = {
        ItemID = 6084,
        Name = 'Item_Name_6084',
        Des = 'Item_Des_6084',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6085] = {
        ItemID = 6085,
        Name = 'Item_Name_6085',
        Des = 'Item_Des_6085',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6086] = {
        ItemID = 6086,
        Name = 'Item_Name_6086',
        Des = 'Item_Des_6086',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6087] = {
        ItemID = 6087,
        Name = 'Item_Name_6087',
        Des = 'Item_Des_6087',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6088] = {
        ItemID = 6088,
        Name = 'Item_Name_6088',
        Des = 'Item_Des_6088',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6089] = {
        ItemID = 6089,
        Name = 'Item_Name_6089',
        Des = 'Item_Des_6089',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6090] = {
        ItemID = 6090,
        Name = 'Item_Name_6090',
        Des = 'Item_Des_6090',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6091] = {
        ItemID = 6091,
        Name = 'Item_Name_6091',
        Des = 'Item_Des_6091',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    },
    [6092] = {
        ItemID = 6092,
        Name = 'Item_Name_6092',
        Des = 'Item_Des_6092',
        Icon = 'RewardItem_Icon',
        UseCD = 0.5,
        UseSoundID = 0,
        UseAnimName = ''
    }
}

return ItemXls
