--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//ItemPool.xlsx

local ItemPoolXls = {
    [1] = {
        [1] = {
            PoolId = 1,
            InnerId = 1,
            ItemId = 6001,
            Weight = 50
        },
        [2] = {
            PoolId = 1,
            InnerId = 2,
            ItemId = 6002,
            Weight = 300
        },
        [3] = {
            PoolId = 1,
            InnerId = 3,
            ItemId = 6003,
            Weight = 100
        },
        [4] = {
            PoolId = 1,
            InnerId = 4,
            ItemId = 6004,
            Weight = 1000
        }
    },
    [2] = {
        [1] = {
            PoolId = 2,
            InnerId = 1,
            ItemId = 6005,
            Weight = 200
        },
        [2] = {
            PoolId = 2,
            InnerId = 2,
            ItemId = 6006,
            Weight = 500
        },
        [3] = {
            PoolId = 2,
            InnerId = 3,
            ItemId = 6007,
            Weight = 1000
        }
    },
    [3] = {
        [1] = {
            PoolId = 3,
            InnerId = 1,
            ItemId = 6008,
            Weight = 600
        },
        [2] = {
            PoolId = 3,
            InnerId = 2,
            ItemId = 6009,
            Weight = 1000
        },
        [3] = {
            PoolId = 3,
            InnerId = 3,
            ItemId = 6010,
            Weight = 600
        }
    },
    [4] = {
        [1] = {
            PoolId = 4,
            InnerId = 1,
            ItemId = 6011,
            Weight = 600
        },
        [2] = {
            PoolId = 4,
            InnerId = 2,
            ItemId = 6009,
            Weight = 1000
        },
        [3] = {
            PoolId = 4,
            InnerId = 3,
            ItemId = 6010,
            Weight = 600
        }
    },
    [5] = {
        [1] = {
            PoolId = 5,
            InnerId = 1,
            ItemId = 6012,
            Weight = 1000
        },
        [2] = {
            PoolId = 5,
            InnerId = 2,
            ItemId = 6013,
            Weight = 1000
        }
    },
    [6] = {
        [1] = {
            PoolId = 6,
            InnerId = 1,
            ItemId = 6014,
            Weight = 100
        },
        [2] = {
            PoolId = 6,
            InnerId = 2,
            ItemId = 6015,
            Weight = 400
        },
        [3] = {
            PoolId = 6,
            InnerId = 3,
            ItemId = 6016,
            Weight = 1000
        },
        [4] = {
            PoolId = 6,
            InnerId = 4,
            ItemId = 6017,
            Weight = 200
        }
    },
    [7] = {
        [1] = {
            PoolId = 7,
            InnerId = 1,
            ItemId = 6018,
            Weight = 1000
        },
        [2] = {
            PoolId = 7,
            InnerId = 2,
            ItemId = 6019,
            Weight = 200
        },
        [3] = {
            PoolId = 7,
            InnerId = 3,
            ItemId = 6020,
            Weight = 400
        }
    },
    [8] = {
        [1] = {
            PoolId = 8,
            InnerId = 1,
            ItemId = 6021,
            Weight = 1000
        },
        [2] = {
            PoolId = 8,
            InnerId = 2,
            ItemId = 6022,
            Weight = 1000
        }
    },
    [9] = {
        [1] = {
            PoolId = 9,
            InnerId = 1,
            ItemId = 6023,
            Weight = 1000
        },
        [2] = {
            PoolId = 9,
            InnerId = 2,
            ItemId = 6024,
            Weight = 600
        },
        [3] = {
            PoolId = 9,
            InnerId = 3,
            ItemId = 6025,
            Weight = 800
        },
        [4] = {
            PoolId = 9,
            InnerId = 4,
            ItemId = 6026,
            Weight = 400
        },
        [5] = {
            PoolId = 9,
            InnerId = 5,
            ItemId = 6027,
            Weight = 200
        },
        [6] = {
            PoolId = 9,
            InnerId = 6,
            ItemId = 6028,
            Weight = 100
        },
        [7] = {
            PoolId = 9,
            InnerId = 7,
            ItemId = 6029,
            Weight = 100
        },
        [8] = {
            PoolId = 9,
            InnerId = 8,
            ItemId = 6030,
            Weight = 100
        },
        [9] = {
            PoolId = 9,
            InnerId = 9,
            ItemId = 6031,
            Weight = 800
        },
        [10] = {
            PoolId = 9,
            InnerId = 10,
            ItemId = 6032,
            Weight = 800
        },
        [11] = {
            PoolId = 9,
            InnerId = 11,
            ItemId = 6033,
            Weight = 800
        }
    },
    [10] = {
        [1] = {
            PoolId = 10,
            InnerId = 1,
            ItemId = 6034,
            Weight = 1000
        },
        [2] = {
            PoolId = 10,
            InnerId = 2,
            ItemId = 6039,
            Weight = 1000
        },
        [3] = {
            PoolId = 10,
            InnerId = 3,
            ItemId = 1002,
            Weight = 200
        }
    },
    [11] = {
        [1] = {
            PoolId = 11,
            InnerId = 1,
            ItemId = 6031,
            Weight = 1000
        },
        [2] = {
            PoolId = 11,
            InnerId = 2,
            ItemId = 6032,
            Weight = 1000
        },
        [3] = {
            PoolId = 11,
            InnerId = 3,
            ItemId = 6033,
            Weight = 1000
        },
        [4] = {
            PoolId = 11,
            InnerId = 4,
            ItemId = 6034,
            Weight = 1000
        },
        [5] = {
            PoolId = 11,
            InnerId = 5,
            ItemId = 6035,
            Weight = 200
        },
        [6] = {
            PoolId = 11,
            InnerId = 6,
            ItemId = 6036,
            Weight = 100
        },
        [7] = {
            PoolId = 11,
            InnerId = 7,
            ItemId = 6037,
            Weight = 500
        },
        [8] = {
            PoolId = 11,
            InnerId = 8,
            ItemId = 6038,
            Weight = 200
        },
        [9] = {
            PoolId = 11,
            InnerId = 9,
            ItemId = 6039,
            Weight = 1000
        },
        [10] = {
            PoolId = 11,
            InnerId = 10,
            ItemId = 6022,
            Weight = 600
        },
        [11] = {
            PoolId = 11,
            InnerId = 11,
            ItemId = 6023,
            Weight = 750
        }
    },
    [12] = {
        [1] = {
            PoolId = 12,
            InnerId = 1,
            ItemId = 1000,
            Weight = 1000
        }
    },
    [13] = {
        [1] = {
            PoolId = 13,
            InnerId = 1,
            ItemId = 1000,
            Weight = 1000
        }
    },
    [14] = {
        [1] = {
            PoolId = 14,
            InnerId = 1,
            ItemId = 1000,
            Weight = 1000
        }
    },
    [15] = {
        [1] = {
            PoolId = 15,
            InnerId = 1,
            ItemId = 1000,
            Weight = 1000
        }
    },
    [16] = {
        [1] = {
            PoolId = 16,
            InnerId = 1,
            ItemId = 5012,
            Weight = 1000
        },
        [2] = {
            PoolId = 16,
            InnerId = 2,
            ItemId = 5013,
            Weight = 1000
        },
        [3] = {
            PoolId = 16,
            InnerId = 3,
            ItemId = 5014,
            Weight = 1000
        },
        [4] = {
            PoolId = 16,
            InnerId = 4,
            ItemId = 5015,
            Weight = 1000
        }
    },
    [17] = {
        [1] = {
            PoolId = 17,
            InnerId = 1,
            ItemId = 1000,
            Weight = 1000
        },
        [2] = {
            PoolId = 17,
            InnerId = 2,
            ItemId = 1000,
            Weight = 1000
        },
        [3] = {
            PoolId = 17,
            InnerId = 3,
            ItemId = 1000,
            Weight = 1000
        },
        [4] = {
            PoolId = 17,
            InnerId = 4,
            ItemId = 1000,
            Weight = 1000
        }
    }
}

return ItemPoolXls
