--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//LanguagePack.xls

local LanguagePackXls = {
    GameInfo_GameName_1 = {
        ID = 'GameInfo_GameName_1',
        CHS = '打猎',
        CHT = '',
        EN = 'Hunting',
        JP = ''
    },
    GameInfo_GameName_2 = {
        ID = 'GameInfo_GameName_2',
        CHS = '打地鼠',
        CHT = '',
        EN = 'Whack-A-Mole',
        JP = ''
    },
    GameInfo_GameName_3 = {
        ID = 'GameInfo_GameName_3',
        CHS = '迷宫',
        CHT = '',
        EN = 'Maze',
        JP = ''
    },
    GameInfo_GameName_4 = {
        ID = 'GameInfo_GameName_4',
        CHS = '人间大炮',
        CHT = '',
        EN = 'Cannon',
        JP = ''
    },
    GameInfo_GameName_5 = {
        ID = 'GameInfo_GameName_5',
        CHS = '青蛙过河',
        CHT = '',
        EN = 'Frog',
        JP = ''
    },
    GameInfo_GameName_6 = {
        ID = 'GameInfo_GameName_6',
        CHS = '热气球',
        CHT = '',
        EN = 'Zeppelin',
        JP = ''
    },
    GameInfo_GameName_7 = {
        ID = 'GameInfo_GameName_7',
        CHS = '种花',
        CHT = '',
        EN = 'Farming',
        JP = ''
    },
    GameInfo_GameName_8 = {
        ID = 'GameInfo_GameName_8',
        CHS = '赛蜗牛',
        CHT = '',
        EN = 'Snail Battle',
        JP = ''
    },
    GameInfo_GameName_9 = {
        ID = 'GameInfo_GameName_9',
        CHS = '竞速',
        CHT = '',
        EN = 'Racing',
        JP = ''
    },
    GameInfo_GameName_10 = {
        ID = 'GameInfo_GameName_10',
        CHS = '摇摇椅',
        CHT = '',
        EN = 'Chair Club',
        JP = ''
    },
    GameInfo_GameName_11 = {
        ID = 'GameInfo_GameName_11',
        CHS = '斗怪物',
        CHT = '',
        EN = 'Moster Battle',
        JP = ''
    }
}

return LanguagePackXls
