--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//Item.xlsm

local BuffXls = {
    [1] = {
        BUFF = 1,
        SizeChange = 2.0,
        HeadSizeChange = 2.0,
        WidthChange = 1.0,
        KeepEffect = nil,
        SpeedChange = 1.5,
        JumpChange = 2.0,
        GravityChange = 0.5,
        SkinId = 1,
        KeepAnim = ''
    },
    [2] = {
        BUFF = 2,
        SizeChange = 1.0,
        HeadSizeChange = 1.0,
        WidthChange = 1.0,
        KeepEffect = {[2]=fire},
        SpeedChange = 1.2,
        JumpChange = 1.0,
        GravityChange = 1.0,
        SkinId = nil,
        KeepAnim = 'Onfire'
    }
}

return BuffXls
