--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//Item.xlsm

local BuffXls = {
    [1] = {
        ID = 1,
        BuffCoverIDList = {0},
        AvatarHeight_Overlay = 2.0,
        AvatarHeadSize_Overlay = 2.0,
        AvatarWidth_Overlay = 1.0,
        HeadEffect_Overlay = 'Fire',
        BodyEffect_Overlay = 'Fire',
        FootEffect_Overlay = 'Fire',
        WalkSpeed_Overlay = 2.0,
        JumpUpVelocity_Overlay = 2.0,
        GravityScale_Overlay = 1.0,
        SkinID_Cover = 1,
        AnimState_Cover = '',
        EnableEquipable_Cover = true
    },
    [2] = {
        ID = 2,
        BuffCoverIDList = {1},
        AvatarHeight_Overlay = 1.0,
        AvatarHeadSize_Overlay = 1.0,
        AvatarWidth_Overlay = 1.0,
        HeadEffect_Overlay = '',
        BodyEffect_Overlay = '',
        FootEffect_Overlay = '',
        WalkSpeed_Overlay = 1.0,
        JumpUpVelocity_Overlay = 1.0,
        GravityScale_Overlay = 1.0,
        SkinID_Cover = 1,
        AnimState_Cover = 'TwoHandedSwordIdle',
        EnableEquipable_Cover = true
    },
    [3] = {
        ID = 3,
        BuffCoverIDList = {1},
        AvatarHeight_Overlay = 1.0,
        AvatarHeadSize_Overlay = 1.0,
        AvatarWidth_Overlay = 1.0,
        HeadEffect_Overlay = '',
        BodyEffect_Overlay = '',
        FootEffect_Overlay = '',
        WalkSpeed_Overlay = 1.0,
        JumpUpVelocity_Overlay = 1.0,
        GravityScale_Overlay = 1.0,
        SkinID_Cover = 1,
        AnimState_Cover = 'BowIdle',
        EnableEquipable_Cover = true
    }
}

return BuffXls
