--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//qte摇摇椅策划案.xlsx

local ChairInfoXls = {
    C1 = {
        ID = 'C1',
        Archetype = 'Chair_Normal',
        Type = 'Normal',
        Position = Vector3(-145.712,  -3.9355,  109.495),
        Rotation = EulerDegree(0,  0,  0)
    },
    C2 = {
        ID = 'C2',
        Archetype = 'Chair_Normal',
        Type = 'Normal',
        Position = Vector3(-147.284,  -3.9355,  109.495),
        Rotation = EulerDegree(0,  0,  0)
    },
    C3 = {
        ID = 'C3',
        Archetype = 'Chair_Normal',
        Type = 'Normal',
        Position = Vector3(-148.989,  -3.9355,  109.495),
        Rotation = EulerDegree(0,  0,  0)
    },
    C4 = {
        ID = 'C4',
        Archetype = 'Chair_Normal',
        Type = 'Normal',
        Position = Vector3(-150.788,  -3.9355,  109.495),
        Rotation = EulerDegree(0,  0,  0)
    },
    C5 = {
        ID = 'C5',
        Archetype = 'Chair_QTE',
        Type = 'QTE',
        Position = Vector3(-135.347,  -3.3005,  110.637),
        Rotation = EulerDegree(0,  0,  0)
    }
}

return ChairInfoXls
