--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//Item.xlsm

local TaskItemXls = {
    [5001] = {
        ItemID = 5001,
        Npc = {14},
        RewardItem = 0,
        RewardGold = 50,
        NpcText = 'TaskItem_NpcText_5001'
    },
    [5002] = {
        ItemID = 5002,
        Npc = {13},
        RewardItem = 0,
        RewardGold = 50,
        NpcText = 'TaskItem_NpcText_5002'
    },
    [5003] = {
        ItemID = 5003,
        Npc = {3},
        RewardItem = 0,
        RewardGold = 50,
        NpcText = 'TaskItem_NpcText_5003'
    },
    [5004] = {
        ItemID = 5004,
        Npc = {5},
        RewardItem = 0,
        RewardGold = 50,
        NpcText = 'TaskItem_NpcText_5004'
    },
    [5005] = {
        ItemID = 5005,
        Npc = {6},
        RewardItem = 0,
        RewardGold = 50,
        NpcText = 'TaskItem_NpcText_5005'
    },
    [5006] = {
        ItemID = 5006,
        Npc = {12},
        RewardItem = 0,
        RewardGold = 200,
        NpcText = 'TaskItem_NpcText_5006'
    },
    [5007] = {
        ItemID = 5007,
        Npc = {3},
        RewardItem = 2001,
        RewardGold = 200,
        NpcText = 'TaskItem_NpcText_5007'
    }
}

return TaskItemXls
