--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//GameHunting.xlsx

local AnimalXls = {
    [1] = {
        ID = 1,
        Name = '麋鹿',
        ArchetypeName = 'Animal_Reindeer',
        DefMoveSpeed = 10.0,
        ScaredMoveSpeed = 10.0,
        IdleAnimationName = {'Idle', 'Idle02'},
        IdleAnimationDurRange = {5, 20},
        MoveAnimationName = {'Run'},
        MoveAnimationDurRange = {2, 4},
        DeadAnimationName = {},
        Weight = 50
    }
}

return AnimalXls
