--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//社交岛经济系统.xlsx

local gameInfoXls = {
    [1] = {
        GameId = 1,
        GameName = '打猎'
    },
    [2] = {
        GameId = 2,
        GameName = '打地鼠'
    },
    [3] = {
        GameId = 3,
        GameName = '迷宫'
    },
    [4] = {
        GameId = 4,
        GameName = '人间大炮'
    },
    [5] = {
        GameId = 5,
        GameName = '青蛙过河'
    },
    [6] = {
        GameId = 6,
        GameName = '热气球'
    },
    [7] = {
        GameId = 7,
        GameName = '种花'
    },
    [8] = {
        GameId = 8,
        GameName = '赛蜗牛'
    },
    [9] = {
        GameId = 9,
        GameName = '竞速'
    },
    [10] = {
        GameId = 10,
        GameName = '摇摇椅'
    },
    [11] = {
        GameId = 11,
        GameName = '斗怪物'
    }
}

return gameInfoXls
