--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: .//Pet.xlsm

local PetXls = {
    [1] = {
        ID = 1,
        Name = '麋鹿',
        ArchetypeName = 'Pet_Reindeer',
        DefMoveSpeed = 4.0,
        FastMoveSpeed = 8.0,
        FastMoveAnimation = {},
        IdleAnimation = {'Idle', 'Idle02'},
        ToIdleAnimation = '',
        MoveAnimation = {'Run'},
        ToMoveAnimation = '',
        IsNew = false,
        AnimationPath = ''
    },
    [2] = {
        ID = 2,
        Name = '黄野猪',
        ArchetypeName = 'Pet_Boar001',
        DefMoveSpeed = 3.0,
        FastMoveSpeed = 5.0,
        FastMoveAnimation = {},
        IdleAnimation = {'Idle', 'Idle2'},
        ToIdleAnimation = '',
        MoveAnimation = {'Walk'},
        ToMoveAnimation = '',
        IsNew = false,
        AnimationPath = ''
    },
    [3] = {
        ID = 3,
        Name = '黑野猪',
        ArchetypeName = 'Pet_Boar002',
        DefMoveSpeed = 3.0,
        FastMoveSpeed = 5.0,
        FastMoveAnimation = {},
        IdleAnimation = {'Idle', 'Idle2'},
        ToIdleAnimation = '',
        MoveAnimation = {'Walk'},
        ToMoveAnimation = '',
        IsNew = false,
        AnimationPath = ''
    },
    [5] = {
        ID = 5,
        Name = '山鸡',
        ArchetypeName = 'Pet_Pheasant',
        DefMoveSpeed = 3.0,
        FastMoveSpeed = 5.0,
        FastMoveAnimation = {},
        IdleAnimation = {'Idle', 'Idle2'},
        ToIdleAnimation = '',
        MoveAnimation = {'Walk'},
        ToMoveAnimation = '',
        IsNew = false,
        AnimationPath = ''
    },
    [6] = {
        ID = 6,
        Name = '棕熊',
        ArchetypeName = 'Pet_Bear',
        DefMoveSpeed = 1.5,
        FastMoveSpeed = 3.0,
        FastMoveAnimation = {},
        IdleAnimation = {'Idle', 'Idle2'},
        ToIdleAnimation = '',
        MoveAnimation = {'Walk'},
        ToMoveAnimation = '',
        IsNew = false,
        AnimationPath = ''
    },
    [7] = {
        ID = 7,
        Name = '灰狼',
        ArchetypeName = 'Pet_Wolf',
        DefMoveSpeed = 2.5,
        FastMoveSpeed = 4.0,
        FastMoveAnimation = {},
        IdleAnimation = {'Idle', 'Idle2'},
        ToIdleAnimation = '',
        MoveAnimation = {'Walk'},
        ToMoveAnimation = '',
        IsNew = false,
        AnimationPath = ''
    },
    [101] = {
        ID = 101,
        Name = '幼年白尾鹿',
        ArchetypeName = 'Pet_YoungWhiteTailedDeer',
        DefMoveSpeed = 1.5,
        FastMoveSpeed = 6.0,
        FastMoveAnimation = {'run'},
        IdleAnimation = {'idle', 'idle_02', 'idle_03', 'eat'},
        ToIdleAnimation = '',
        MoveAnimation = {'walk'},
        ToMoveAnimation = '',
        IsNew = true,
        AnimationPath = 'WhiteTailedDeer_002'
    },
    [102] = {
        ID = 102,
        Name = '成年白尾鹿',
        ArchetypeName = 'Pet_WhiteTailedDeer',
        DefMoveSpeed = 1.5,
        FastMoveSpeed = 7.0,
        FastMoveAnimation = {'run'},
        IdleAnimation = {'idle', 'idle_02', 'idle_03', 'eat'},
        ToIdleAnimation = '',
        MoveAnimation = {'walk'},
        ToMoveAnimation = '',
        IsNew = true,
        AnimationPath = 'WhiteTailedDeer_001'
    },
    [103] = {
        ID = 103,
        Name = '蝙蝠',
        ArchetypeName = 'Pet_Bat',
        DefMoveSpeed = 3.0,
        FastMoveSpeed = 6.0,
        FastMoveAnimation = {},
        IdleAnimation = {'fly'},
        ToIdleAnimation = '',
        MoveAnimation = {'fly'},
        ToMoveAnimation = '',
        IsNew = true,
        AnimationPath = 'Bat'
    },
    [104] = {
        ID = 104,
        Name = '火烈鸟',
        ArchetypeName = 'Pet_Flamingos',
        DefMoveSpeed = 1.0,
        FastMoveSpeed = 1.5,
        FastMoveAnimation = {},
        IdleAnimation = {'idle', 'idle_02', 'idle_03', 'eat', 'drinkwater'},
        ToIdleAnimation = '',
        MoveAnimation = {'walk'},
        ToMoveAnimation = '',
        IsNew = true,
        AnimationPath = 'Flamingos_001'
    },
    [105] = {
        ID = 105,
        Name = '幼年绿头鸭',
        ArchetypeName = 'Pet_YoungMallard',
        DefMoveSpeed = 2.0,
        FastMoveSpeed = 4.0,
        FastMoveAnimation = {},
        IdleAnimation = {'idle', 'idle_02', 'idle_03', 'eat', 'cry'},
        ToIdleAnimation = '',
        MoveAnimation = {'walk'},
        ToMoveAnimation = '',
        IsNew = true,
        AnimationPath = 'Mallard_002'
    },
    [106] = {
        ID = 106,
        Name = '成年绿头鸭',
        ArchetypeName = 'Pet_Mallard',
        DefMoveSpeed = 2.0,
        FastMoveSpeed = 5.0,
        FastMoveAnimation = {},
        IdleAnimation = {'idle', 'idle_02', 'idle_03'},
        ToIdleAnimation = '',
        MoveAnimation = {'walk'},
        ToMoveAnimation = '',
        IsNew = true,
        AnimationPath = 'Mallard_001'
    },
    [107] = {
        ID = 107,
        Name = '啄木鸟',
        ArchetypeName = 'Pet_Woodpecker',
        DefMoveSpeed = 4.0,
        FastMoveSpeed = 6.0,
        FastMoveAnimation = {},
        IdleAnimation = {'idle', 'idle_02'},
        ToIdleAnimation = 'fly_down',
        MoveAnimation = {'fly'},
        ToMoveAnimation = 'fly_up',
        IsNew = true,
        AnimationPath = 'Woodpecker_001'
    }
}

return PetXls
