--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//GlobalSetting.xls

local GlobalSettingXls = {
    DefaultLanguage = "EN"
}

return GlobalSettingXls
