--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//GameLotus.xlsx

local LotusChestXls = {
    [1] = {
        Id = 1,
        Model = 'BigChest',
        Content = {1,2,3},
        Weight = 5,
        SpeedEffect = 0.7
    },
    [2] = {
        Id = 2,
        Model = 'MidChest',
        Content = {2,3},
        Weight = 30,
        SpeedEffect = 0.8
    },
    [3] = {
        Id = 3,
        Model = 'SmlChest',
        Content = {3,4},
        Weight = 60,
        SpeedEffect = 0.85
    }
}

return LotusChestXls
