--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//Cook.xlsx

local CookMenuXls = {
    [1] = {
        Id = 1,
        Menu = {7001, 7002, 7003},
        Name = 'CookMenu_Name_1',
        Ico = '',
        Model = 'Meal1',
        BuffId = 49,
        BuffDur = 10.0
    },
    [2] = {
        Id = 2,
        Menu = {7001, 7003, 7004},
        Name = 'CookMenu_Name_2',
        Ico = '',
        Model = 'Meal2',
        BuffId = 50,
        BuffDur = 10.0
    },
    [3] = {
        Id = 3,
        Menu = {7003, 7009, 7001},
        Name = 'CookMenu_Name_3',
        Ico = '',
        Model = 'Meal3',
        BuffId = 51,
        BuffDur = 10.0
    },
    [4] = {
        Id = 4,
        Menu = {7007, 7008, 7004},
        Name = 'CookMenu_Name_4',
        Ico = '',
        Model = 'Meal4',
        BuffId = 52,
        BuffDur = 10.0
    },
    [5] = {
        Id = 5,
        Menu = {},
        Name = 'CookMenu_Name_5',
        Ico = '',
        Model = 'Meal5',
        BuffId = 53,
        BuffDur = 10.0
    },
    [6] = {
        Id = 6,
        Menu = {7004, 7005, 7006},
        Name = 'CookMenu_Name_6',
        Ico = '',
        Model = 'Meal7',
        BuffId = 54,
        BuffDur = 10.0
    },
    [7] = {
        Id = 7,
        Menu = {7005, 7002, 7009},
        Name = 'CookMenu_Name_7',
        Ico = '',
        Model = 'Meal8',
        BuffId = 55,
        BuffDur = 10.0
    },
    [8] = {
        Id = 8,
        Menu = {7003, 7009, 7001},
        Name = 'CookMenu_Name_8',
        Ico = '',
        Model = 'Meal9',
        BuffId = 49,
        BuffDur = 10.0
    },
    [9] = {
        Id = 9,
        Menu = {7006, 7002, 7003},
        Name = 'CookMenu_Name_9',
        Ico = '',
        Model = 'Meal10',
        BuffId = 50,
        BuffDur = 10.0
    },
    [10] = {
        Id = 10,
        Menu = {7002, 7003, 7004},
        Name = 'CookMenu_Name_10',
        Ico = '',
        Model = 'Meal11',
        BuffId = 51,
        BuffDur = 10.0
    },
    [11] = {
        Id = 11,
        Menu = {7002, 7003, 7009},
        Name = 'CookMenu_Name_11',
        Ico = '',
        Model = 'Meal12',
        BuffId = 52,
        BuffDur = 10.0
    },
    [12] = {
        Id = 12,
        Menu = {7005, 7009, 7003},
        Name = 'CookMenu_Name_12',
        Ico = '',
        Model = 'Meal13',
        BuffId = 53,
        BuffDur = 10.0
    },
    [13] = {
        Id = 13,
        Menu = {7001, 7002, 7004},
        Name = 'CookMenu_Name_13',
        Ico = '',
        Model = 'Meal14',
        BuffId = 54,
        BuffDur = 10.0
    },
    [14] = {
        Id = 14,
        Menu = {7006, 7002, 7009},
        Name = 'CookMenu_Name_14',
        Ico = '',
        Model = 'Meal15',
        BuffId = nil,
        BuffDur = 10.0
    },
    [15] = {
        Id = 15,
        Menu = {},
        Name = 'CookMenu_Name_15',
        Ico = '',
        Model = 'Meal6',
        BuffId = nil,
        BuffDur = 10.0
    },
    [16] = {
        Id = 16,
        Menu = {7001, 7002, 7005},
        Name = 'CookMenu_Name_16',
        Ico = '',
        Model = 'Meal16',
        BuffId = 51,
        BuffDur = 10.0
    },
    [17] = {
        Id = 17,
        Menu = {7001, 7002, 7006},
        Name = 'CookMenu_Name_17',
        Ico = '',
        Model = 'Meal16',
        BuffId = 51,
        BuffDur = 10.0
    },
    [18] = {
        Id = 18,
        Menu = {7001, 7002, 7007},
        Name = 'CookMenu_Name_18',
        Ico = '',
        Model = 'Meal16',
        BuffId = 51,
        BuffDur = 10.0
    },
    [19] = {
        Id = 19,
        Menu = {7001, 7002, 7008},
        Name = 'CookMenu_Name_19',
        Ico = '',
        Model = 'Meal16',
        BuffId = 51,
        BuffDur = 10.0
    },
    [20] = {
        Id = 20,
        Menu = {7001, 7003, 7005},
        Name = 'CookMenu_Name_20',
        Ico = '',
        Model = 'Meal2',
        BuffId = 50,
        BuffDur = 10.0
    },
    [21] = {
        Id = 21,
        Menu = {7001, 7003, 7006},
        Name = 'CookMenu_Name_21',
        Ico = '',
        Model = 'Meal2',
        BuffId = 50,
        BuffDur = 10.0
    },
    [22] = {
        Id = 22,
        Menu = {7001, 7003, 7007},
        Name = 'CookMenu_Name_22',
        Ico = '',
        Model = 'Meal2',
        BuffId = 50,
        BuffDur = 10.0
    },
    [23] = {
        Id = 23,
        Menu = {7001, 7003, 7008},
        Name = 'CookMenu_Name_23',
        Ico = '',
        Model = 'Meal2',
        BuffId = 50,
        BuffDur = 10.0
    },
    [24] = {
        Id = 24,
        Menu = {7003, 7009, 7002},
        Name = 'CookMenu_Name_24',
        Ico = '',
        Model = 'Meal3',
        BuffId = 51,
        BuffDur = 10.0
    },
    [25] = {
        Id = 25,
        Menu = {7007, 7005, 7006},
        Name = 'CookMenu_Name_25',
        Ico = '',
        Model = 'Meal7',
        BuffId = 54,
        BuffDur = 10.0
    },
    [26] = {
        Id = 26,
        Menu = {7004, 7007, 7006},
        Name = 'CookMenu_Name_26',
        Ico = '',
        Model = 'Meal7',
        BuffId = 54,
        BuffDur = 10.0
    },
    [27] = {
        Id = 27,
        Menu = {7004, 7005, 7007},
        Name = 'CookMenu_Name_27',
        Ico = '',
        Model = 'Meal7',
        BuffId = 54,
        BuffDur = 10.0
    },
    [28] = {
        Id = 28,
        Menu = {7004, 7008, 7006},
        Name = 'CookMenu_Name_28',
        Ico = '',
        Model = 'Meal7',
        BuffId = 54,
        BuffDur = 10.0
    },
    [29] = {
        Id = 29,
        Menu = {7004, 7008, 7008},
        Name = 'CookMenu_Name_29',
        Ico = '',
        Model = 'Meal7',
        BuffId = 54,
        BuffDur = 10.0
    },
    [30] = {
        Id = 30,
        Menu = {7003, 7009, 7002},
        Name = 'CookMenu_Name_30',
        Ico = '',
        Model = 'Meal9',
        BuffId = 49,
        BuffDur = 10.0
    }
}

return CookMenuXls
