--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//GameChair.xlsx

local ChairGlobalConfigXls = {
    SpiritDecayRate = {
        Key = 'SpiritDecayRate',
        Value = {[20]=0.4,[15]=0.3,[10]=0.25,[0]=0.2}
    },
    SpiritIncrease = {
        Key = 'SpiritIncrease',
        Value = 0.1
    },
    FlyingTime = {
        Key = 'FlyingTime',
        Value = 1.0
    },
    FlyingVelocity = {
        Key = 'FlyingVelocity',
        Value = 20.0
    },
    ReturningVelocity = {
        Key = 'ReturningVelocity',
        Value = 5.0
    },
    BaseAngularVelocity = {
        Key = 'BaseAngularVelocity',
        Value = {x=5,y=5,z=5}
    },
    RatioRandomRange = {
        Key = 'RatioRandomRange',
        Value = 15.0
    },
    JetingDuration = {
        Key = 'JetingDuration',
        Value = 1.0
    },
    BaseLinearVelocity = {
        Key = 'BaseLinearVelocity',
        Value = {x=5,y=0,z=5}
    }
}

return ChairGlobalConfigXls
