--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: .//PlayerActState.xlsx

local PlayerActModeXls = {
    [0] = {
        ID = 0,
        Name = 'disable',
        ActNextState = ''
    },
    [1] = {
        ID = 1,
        Name = 'stand',
        ActNextState = 'IdleState'
    },
    [2] = {
        ID = 2,
        Name = 'sit',
        ActNextState = 'SitState'
    },
    [3] = {
        ID = 3,
        Name = 'jump',
        ActNextState = ''
    },
    [4] = {
        ID = 4,
        Name = 'fall',
        ActNextState = ''
    },
    [5] = {
        ID = 5,
        Name = 'bow',
        ActNextState = 'BowIdleState'
    },
    [6] = {
        ID = 6,
        Name = 'swim',
        ActNextState = ''
    }
}

return PlayerActModeXls
