--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//ArrowTargetConfig.xlsx

local ArrowTargetXls = {
    [1] = {
        ID = 1,
        Name = '靶子',
        HitEffect = 'ArrowTartgetHitEffect',
        RewardCoin = 1,
        ResetTime = 3.0
    },
    [2] = {
        ID = 2,
        Name = '苹果',
        HitEffect = 'ArrowTartgetHitEffect',
        RewardCoin = 0,
        ResetTime = 60.0
    },
    [3] = {
        ID = 3,
        Name = '飞行宝箱',
        HitEffect = 'ArrowTartgetHitEffect',
        RewardCoin = 0,
        ResetTime = 300.0
    },
    [4] = {
        ID = 4,
        Name = '树靶子',
        HitEffect = 'ArrowTartgetHitEffect',
        RewardCoin = 3,
        ResetTime = 7.0
    }
}

return ArrowTargetXls
