--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//GameMole.xlsx

local MoleGlobalConfigXls = {
    UFOPitNum = {
        Key = 'UFOPitNum',
        Value = 10.0
    },
    MazePitNum = {
        Key = 'MazePitNum',
        Value = 10.0
    },
    RefreshTime = {
        Key = 'RefreshTime',
        Value = 10000.0
    }
}

return MoleGlobalConfigXls
