--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//Item.xlsm

local ThrowItemXls = {
    [3001] = {
        ItemID = 3001,
        Model = '',
        AnimUse = 'TurnAround',
        AttckCD = '3.0',
        AnimState = 6,
        Offset = nil,
        Angle = nil,
        Range = 10.0,
        ExplosionRange = 1.5,
        HealthChange = 100,
        UseAddBuff = {2, 3, 10, 4, 5, 6, 7, 8, 9},
        HitAddBuff = nil,
        HitRemoveBuff = nil,
        HitEffect = 'Fire_Explosion',
        HitAnim = '',
        UseSound = '',
        HitSound = '',
        PickItemId = nil,
        PetId = nil,
        PetHealthIncreace = nil,
        PetAttackIncreace = nil
    },
    [3002] = {
        ItemID = 3002,
        Model = 'M_FireBowl',
        AnimUse = 'Equip',
        AttckCD = '1.0',
        AnimState = nil,
        Offset = Vector3(0, 0, 0),
        Angle = EulerDegree(0, 0, 0),
        Range = 20.0,
        ExplosionRange = nil,
        HealthChange = 50,
        UseAddBuff = nil,
        HitAddBuff = nil,
        HitRemoveBuff = nil,
        HitEffect = '',
        HitAnim = '',
        UseSound = '',
        HitSound = '',
        PickItemId = nil,
        PetId = nil,
        PetHealthIncreace = nil,
        PetAttackIncreace = nil
    }
}

return ThrowItemXls
