--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: .//Pet.xlsm

local PetEntry2Xls = {
    [1] = {
        ID = 1,
        Name = '普通',
        Type = 2,
        EffectName = '',
        StrengthRange = {-10, 0},
        SpeedRange = {-10, 0},
        Weight = 270
    },
    [2] = {
        ID = 2,
        Name = '狂战士',
        Type = 2,
        EffectName = '',
        StrengthRange = {0, 0},
        SpeedRange = {0, 20},
        Weight = 60
    },
    [3] = {
        ID = 3,
        Name = '火花塞',
        Type = 2,
        EffectName = '',
        StrengthRange = {-10, 0},
        SpeedRange = {0, 40},
        Weight = 40
    },
    [4] = {
        ID = 4,
        Name = '烧烤',
        Type = 2,
        EffectName = '',
        StrengthRange = {0, 10},
        SpeedRange = {0, 10},
        Weight = 40
    },
    [5] = {
        ID = 5,
        Name = '冷鲜肉',
        Type = 2,
        EffectName = '',
        StrengthRange = {0, 30},
        SpeedRange = {0, 0},
        Weight = 40
    },
    [6] = {
        ID = 6,
        Name = '生化战士',
        Type = 2,
        EffectName = '',
        StrengthRange = {-10, 10},
        SpeedRange = {0, 30},
        Weight = 40
    },
    [7] = {
        ID = 7,
        Name = '摇滚巨星',
        Type = 2,
        EffectName = '',
        StrengthRange = {0, 10},
        SpeedRange = {-10, 20},
        Weight = 20
    },
    [8] = {
        ID = 8,
        Name = '麻瓜',
        Type = 2,
        EffectName = '',
        StrengthRange = {-20, 0},
        SpeedRange = {-20, 0},
        Weight = 60
    },
    [9] = {
        ID = 9,
        Name = '飞行员',
        Type = 2,
        EffectName = '',
        StrengthRange = {10, 20},
        SpeedRange = {0, 20},
        Weight = 20
    },
    [10] = {
        ID = 10,
        Name = '程序员',
        Type = 2,
        EffectName = '',
        StrengthRange = {0, 30},
        SpeedRange = {0, 30},
        Weight = 10
    }
}

return PetEntry2Xls
