--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//Item.xlsm

local RewardItemXls = {
    [6001] = {
        ItemID = 6001,
        RewardGold = 100
    },
    [6002] = {
        ItemID = 6002,
        RewardGold = 40
    },
    [6003] = {
        ItemID = 6003,
        RewardGold = 80
    },
    [6004] = {
        ItemID = 6004,
        RewardGold = 20
    },
    [6005] = {
        ItemID = 6005,
        RewardGold = 40
    },
    [6006] = {
        ItemID = 6006,
        RewardGold = 10
    },
    [6007] = {
        ItemID = 6007,
        RewardGold = 5
    },
    [6008] = {
        ItemID = 6008,
        RewardGold = 60
    },
    [6009] = {
        ItemID = 6009,
        RewardGold = 40
    },
    [6010] = {
        ItemID = 6010,
        RewardGold = 60
    },
    [6011] = {
        ItemID = 6011,
        RewardGold = 80
    },
    [6012] = {
        ItemID = 6012,
        RewardGold = 20
    },
    [6013] = {
        ItemID = 6013,
        RewardGold = 35
    },
    [6014] = {
        ItemID = 6014,
        RewardGold = 120
    },
    [6015] = {
        ItemID = 6015,
        RewardGold = 80
    },
    [6016] = {
        ItemID = 6016,
        RewardGold = 60
    },
    [6017] = {
        ItemID = 6017,
        RewardGold = 100
    },
    [6018] = {
        ItemID = 6018,
        RewardGold = 20
    },
    [6019] = {
        ItemID = 6019,
        RewardGold = 80
    },
    [6020] = {
        ItemID = 6020,
        RewardGold = 60
    },
    [6021] = {
        ItemID = 6021,
        RewardGold = 20
    },
    [6022] = {
        ItemID = 6022,
        RewardGold = 20
    },
    [6023] = {
        ItemID = 6023,
        RewardGold = 5
    },
    [6024] = {
        ItemID = 6024,
        RewardGold = 40
    },
    [6025] = {
        ItemID = 6025,
        RewardGold = 20
    },
    [6026] = {
        ItemID = 6026,
        RewardGold = 60
    },
    [6027] = {
        ItemID = 6027,
        RewardGold = 80
    },
    [6028] = {
        ItemID = 6028,
        RewardGold = 100
    },
    [6029] = {
        ItemID = 6029,
        RewardGold = 120
    },
    [6030] = {
        ItemID = 6030,
        RewardGold = 120
    },
    [6031] = {
        ItemID = 6031,
        RewardGold = 20
    },
    [6032] = {
        ItemID = 6032,
        RewardGold = 5
    },
    [6033] = {
        ItemID = 6033,
        RewardGold = 5
    },
    [6034] = {
        ItemID = 6034,
        RewardGold = 5
    },
    [6035] = {
        ItemID = 6035,
        RewardGold = 40
    },
    [6036] = {
        ItemID = 6036,
        RewardGold = 50
    },
    [6037] = {
        ItemID = 6037,
        RewardGold = 20
    },
    [6038] = {
        ItemID = 6038,
        RewardGold = 20
    },
    [6039] = {
        ItemID = 6039,
        RewardGold = 5
    },
    [6040] = {
        ItemID = 6040,
        RewardGold = 10
    },
    [6041] = {
        ItemID = 6041,
        RewardGold = 15
    },
    [6042] = {
        ItemID = 6042,
        RewardGold = 10
    },
    [6043] = {
        ItemID = 6043,
        RewardGold = 5
    },
    [6044] = {
        ItemID = 6044,
        RewardGold = 15
    },
    [6045] = {
        ItemID = 6045,
        RewardGold = 15
    },
    [6046] = {
        ItemID = 6046,
        RewardGold = 20
    },
    [6047] = {
        ItemID = 6047,
        RewardGold = 20
    },
    [6048] = {
        ItemID = 6048,
        RewardGold = 20
    },
    [6049] = {
        ItemID = 6049,
        RewardGold = 15
    },
    [6050] = {
        ItemID = 6050,
        RewardGold = 15
    },
    [6051] = {
        ItemID = 6051,
        RewardGold = 15
    },
    [6052] = {
        ItemID = 6052,
        RewardGold = 10
    },
    [6053] = {
        ItemID = 6053,
        RewardGold = 15
    },
    [6054] = {
        ItemID = 6054,
        RewardGold = 10
    },
    [6055] = {
        ItemID = 6055,
        RewardGold = 30
    },
    [6056] = {
        ItemID = 6056,
        RewardGold = 15
    },
    [6057] = {
        ItemID = 6057,
        RewardGold = 20
    },
    [6058] = {
        ItemID = 6058,
        RewardGold = 20
    },
    [6059] = {
        ItemID = 6059,
        RewardGold = 10
    },
    [6060] = {
        ItemID = 6060,
        RewardGold = 10
    },
    [6061] = {
        ItemID = 6061,
        RewardGold = 15
    },
    [6062] = {
        ItemID = 6062,
        RewardGold = 20
    },
    [6063] = {
        ItemID = 6063,
        RewardGold = 35
    },
    [6064] = {
        ItemID = 6064,
        RewardGold = 100
    },
    [6065] = {
        ItemID = 6065,
        RewardGold = 10
    },
    [6066] = {
        ItemID = 6066,
        RewardGold = 10
    },
    [6067] = {
        ItemID = 6067,
        RewardGold = 15
    },
    [6068] = {
        ItemID = 6068,
        RewardGold = 5
    },
    [6069] = {
        ItemID = 6069,
        RewardGold = 10
    },
    [6070] = {
        ItemID = 6070,
        RewardGold = 5
    },
    [6071] = {
        ItemID = 6071,
        RewardGold = 5
    },
    [6072] = {
        ItemID = 6072,
        RewardGold = 5
    },
    [6073] = {
        ItemID = 6073,
        RewardGold = 10
    },
    [6074] = {
        ItemID = 6074,
        RewardGold = 15
    },
    [6075] = {
        ItemID = 6075,
        RewardGold = 300
    },
    [6076] = {
        ItemID = 6076,
        RewardGold = 20
    },
    [6077] = {
        ItemID = 6077,
        RewardGold = 25
    },
    [6078] = {
        ItemID = 6078,
        RewardGold = 30
    },
    [6079] = {
        ItemID = 6079,
        RewardGold = 10
    },
    [6080] = {
        ItemID = 6080,
        RewardGold = 20
    },
    [6081] = {
        ItemID = 6081,
        RewardGold = 10
    },
    [6082] = {
        ItemID = 6082,
        RewardGold = 10
    },
    [6083] = {
        ItemID = 6083,
        RewardGold = 15
    },
    [6084] = {
        ItemID = 6084,
        RewardGold = 10
    },
    [6085] = {
        ItemID = 6085,
        RewardGold = 10
    },
    [6086] = {
        ItemID = 6086,
        RewardGold = 20
    },
    [6087] = {
        ItemID = 6087,
        RewardGold = 20
    },
    [6088] = {
        ItemID = 6088,
        RewardGold = 20
    },
    [6089] = {
        ItemID = 6089,
        RewardGold = 150
    },
    [6090] = {
        ItemID = 6090,
        RewardGold = 5
    },
    [6091] = {
        ItemID = 6091,
        RewardGold = 20
    },
    [6092] = {
        ItemID = 6092,
        RewardGold = 5
    }
}

return RewardItemXls
