--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//Item.xlsm

local SkinXls = {
    [1] = {
        ID = 1,
        --Gender = 'Male',
        Head = 'DefaultMale',
        Clothes = 'RedJacket',
        Trousers = 'Male_Leg_PantsLRobtEva_001',
        Hair = 'Hair_Green01M',
        HairColor = '',
        Hands = '',
        Shoes = 'Male_SpaceBoots',
        SkinColor = 'Color2',
        HeadAccessory = 'Male_Owl_Helmet',
        FaceAccessory = 'Glasses',
        BodyAccessory = '',
        Eyes = '',
        EyesColor = '',
        Brows = '',
        Nose = '',
        Mouth = '',
        Beard = '',
        FaceDecoration = ''
    }
}

return SkinXls
