--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//Item.xlsm

local UsableItemXls = {
    [3001] = {
        ItemID = 3001,
        Range = 10.0,
        HealthChange = 100,
        UseAddBuffDur = 0.0,
        UseAddBuffID = 0,
        HitAddBuffID = 0,
        HitAddBuffDur = 0.0,
        HitRemoveBuffID = 0,
        HitEffectName = 'nil',
        HitSound = '0.0',
        Hunt = false,
        Mole = true
    },
    [3002] = {
        ItemID = 3002,
        Range = nil,
        HealthChange = nil,
        UseAddBuffDur = 120.0,
        UseAddBuffID = 25,
        HitAddBuffID = nil,
        HitAddBuffDur = nil,
        HitRemoveBuffID = nil,
        HitEffectName = '',
        HitSound = '',
        Hunt = nil,
        Mole = nil
    },
    [3003] = {
        ItemID = 3003,
        Range = nil,
        HealthChange = nil,
        UseAddBuffDur = 120.0,
        UseAddBuffID = 26,
        HitAddBuffID = nil,
        HitAddBuffDur = nil,
        HitRemoveBuffID = nil,
        HitEffectName = '',
        HitSound = '',
        Hunt = nil,
        Mole = nil
    },
    [3004] = {
        ItemID = 3004,
        Range = nil,
        HealthChange = nil,
        UseAddBuffDur = 120.0,
        UseAddBuffID = 6,
        HitAddBuffID = nil,
        HitAddBuffDur = nil,
        HitRemoveBuffID = nil,
        HitEffectName = '',
        HitSound = '',
        Hunt = nil,
        Mole = nil
    },
    [3005] = {
        ItemID = 3005,
        Range = nil,
        HealthChange = nil,
        UseAddBuffDur = 120.0,
        UseAddBuffID = 27,
        HitAddBuffID = nil,
        HitAddBuffDur = nil,
        HitRemoveBuffID = nil,
        HitEffectName = '',
        HitSound = '',
        Hunt = nil,
        Mole = nil
    },
    [3006] = {
        ItemID = 3006,
        Range = nil,
        HealthChange = nil,
        UseAddBuffDur = 120.0,
        UseAddBuffID = 28,
        HitAddBuffID = nil,
        HitAddBuffDur = nil,
        HitRemoveBuffID = nil,
        HitEffectName = '',
        HitSound = '',
        Hunt = nil,
        Mole = nil
    },
    [3007] = {
        ItemID = 3007,
        Range = nil,
        HealthChange = nil,
        UseAddBuffDur = 120.0,
        UseAddBuffID = 13,
        HitAddBuffID = nil,
        HitAddBuffDur = nil,
        HitRemoveBuffID = nil,
        HitEffectName = '',
        HitSound = '',
        Hunt = nil,
        Mole = nil
    }
}

return UsableItemXls
