--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//GameRace.xlsx

local RacePointXls = {
    [1] = {
        [1] = {
            LineId = 1,
            MaxTime = 180.0,
            PointId = 1,
            Pos = Vector3(-79.361389, -9.046194, -23.374607)
        },
        [2] = {
            LineId = 1,
            MaxTime = 180.0,
            PointId = 2,
            Pos = Vector3(-104.098900, -8.273397, -13.463183)
        },
        [3] = {
            LineId = 1,
            MaxTime = 180.0,
            PointId = 3,
            Pos = Vector3(-104.098900, -8.273397, -0.524432)
        }
    },
    [2] = {
        [1] = {
            LineId = 2,
            MaxTime = 180.0,
            PointId = 1,
            Pos = Vector3(-140.434326, -1.827322, 20.748333)
        },
        [2] = {
            LineId = 2,
            MaxTime = 180.0,
            PointId = 2,
            Pos = Vector3(-158.445358, -0.866426, 34.951927)
        },
        [3] = {
            LineId = 2,
            MaxTime = 180.0,
            PointId = 3,
            Pos = Vector3(-158.452499, -0.866426, 49.436337)
        }
    },
    [3] = {
        [1] = {
            LineId = 3,
            MaxTime = 180.0,
            PointId = 1,
            Pos = Vector3(-4.481605, -6.364534, -41.193283)
        },
        [2] = {
            LineId = 3,
            MaxTime = 180.0,
            PointId = 2,
            Pos = Vector3(2.753769, -13.260858, -21.661728)
        },
        [3] = {
            LineId = 3,
            MaxTime = 180.0,
            PointId = 3,
            Pos = Vector3(-15.418204, -13.260858, -10.907187)
        },
        [4] = {
            LineId = 3,
            MaxTime = 180.0,
            PointId = 4,
            Pos = Vector3(-21.867441, -13.260858, -2.643065)
        }
    },
    [4] = {
        [1] = {
            LineId = 4,
            MaxTime = 180.0,
            PointId = 1,
            Pos = Vector3(0.000000, -20.154261, 0.000000)
        },
        [2] = {
            LineId = 4,
            MaxTime = 180.0,
            PointId = 2,
            Pos = Vector3(-8.699747, -20.154261, 4.529496)
        },
        [3] = {
            LineId = 4,
            MaxTime = 180.0,
            PointId = 3,
            Pos = Vector3(-23.786905, -20.154261, 28.940973)
        },
        [4] = {
            LineId = 4,
            MaxTime = 180.0,
            PointId = 4,
            Pos = Vector3(-21.668715, -20.154261, 15.315583)
        }
    }
}

return RacePointXls
