--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//SoundConfig.xlsx

local SoundXls = {
    [1] = {
        ID = 1,
        Type = 'SoundEffect',
        Name = 'Clap',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Clap',
        Info = ''
    },
    [2] = {
        ID = 2,
        Type = 'BGM',
        Name = 'BGM',
        IsLoop = true,
        Volume = 200.0,
        Path = 'Audio/Temp_BGM',
        Info = ''
    }
}

return SoundXls
