--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//GameHunting.xlsx

local AnimalAreaXls = {
    [1] = {
        ID = 1,
        Pos = Vector3(91.231300, -5.830500, 8.811900),
        Range = 25.0,
        AmountMax = 4,
        InitAmount = 8,
        SpawnPoint = {Vector3(97.194099,-10.539500,12.987900),Vector3(107.983803,-10.539500,12.987900),Vector3(87.392601,-10.539500,28.084202)},
        AnimalIDList = {1, 2, 3, 4, 5, 6, 7, 8}
    },
    [2] = {
        ID = 2,
        Pos = Vector3(-141.916702, 1.146000, 26.263000),
        Range = 13.0,
        AmountMax = 2,
        InitAmount = 4,
        SpawnPoint = {Vector3(-135.006897,-0.845700,26.263000),Vector3(-139.241608,-0.845700,31.291901),Vector3(-152.406509,-0.845700,25.132101)},
        AnimalIDList = {9, 10, 11, 12, 13, 14, 15, 16}
    },
    [3] = {
        ID = 3,
        Pos = Vector3(-68.851181, 15.354900, 85.938202),
        Range = 25.0,
        AmountMax = 2,
        InitAmount = 4,
        SpawnPoint = {Vector3(-64.820877,13.711600,89.634903),Vector3(-58.601181,7.993800,69.924698),Vector3(-53.503479,13.700900,86.452003)},
        AnimalIDList = {17, 18, 19, 20, 21, 22, 23, 24}
    },
    [4] = {
        ID = 4,
        Pos = Vector3(-134.171204, 7.798200, 97.470001),
        Range = 30.0,
        AmountMax = 3,
        InitAmount = 6,
        SpawnPoint = {Vector3(-130.210999,-2.350300,97.470001),Vector3(-125.626701,-2.350300,85.143204),Vector3(-139.915710,-2.350300,114.949203)},
        AnimalIDList = {25, 26, 27, 28, 29, 30, 31, 32}
    },
    [5] = {
        ID = 5,
        Pos = Vector3(-94.942108, 1.146000, 19.880098),
        Range = 25.0,
        AmountMax = 2,
        InitAmount = 4,
        SpawnPoint = {Vector3(-83.424911,-10.558600,23.395599),Vector3(-88.207809,-10.558600,40.867401),Vector3(-100.728409,-7.935700,8.450098)},
        AnimalIDList = {33, 34, 35, 36, 37, 38, 39, 40}
    }
}

return AnimalAreaXls
