--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//ItemNew.xlsx

local ConsumableXls = {
    [4025] = {
        ItemID = 4025,
        ModelName = 'Item',
        IsPutBack = false,
        UseEffectName = '',
        ParentNode = 'Bone_R_Hand.RHandWeaponNode',
        Offset = Vector3(0, 0, 0),
        Angle = EulerDegree(0, 0, 0),
        HealthChange = 0,
        UseAddBuffID = 0,
        UseAddBuffDur = 0.0,
        UseRemoveBuffID = 0
    },
    [4026] = {
        ItemID = 4026,
        ModelName = 'Item',
        IsPutBack = false,
        UseEffectName = '',
        ParentNode = 'Bone_R_Hand.RHandWeaponNode',
        Offset = Vector3(0, 0, 0),
        Angle = EulerDegree(0, 0, 0),
        HealthChange = 0,
        UseAddBuffID = 0,
        UseAddBuffDur = 0.0,
        UseRemoveBuffID = 0
    },
    [4027] = {
        ItemID = 4027,
        ModelName = 'Item',
        IsPutBack = false,
        UseEffectName = '',
        ParentNode = 'Bone_R_Hand.RHandWeaponNode',
        Offset = Vector3(0, 0, 0),
        Angle = EulerDegree(0, 0, 0),
        HealthChange = 0,
        UseAddBuffID = 0,
        UseAddBuffDur = 0.0,
        UseRemoveBuffID = 0
    }
}

return ConsumableXls
