--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//社交岛采荷(青蛙过河).xlsx

local LotusLocateInfoXls = {
    [1] = {
        Id = 1,
        Pos = Vector3(-44.728619, -6.027812, 26.637077),
        Rot = EulerDegree(0.000000, 0.000000, 0.000000),
        MinScale = 0.28,
        MaxScale = 0.217
    },
    [2] = {
        Id = 2,
        Pos = Vector3(-38.735844, -5.873641, 29.402515),
        Rot = EulerDegree(0.000000, 0.000000, 0.000000),
        MinScale = 0.28,
        MaxScale = 0.209
    },
    [3] = {
        Id = 3,
        Pos = Vector3(-38.064476, -5.800157, 22.752914),
        Rot = EulerDegree(0.000000, 0.000000, 0.000000),
        MinScale = 0.29,
        MaxScale = 0.244
    },
    [4] = {
        Id = 4,
        Pos = Vector3(-50.124969, -6.027812, 25.166639),
        Rot = EulerDegree(-0.000000, -25.173138, -0.000000),
        MinScale = 0.33,
        MaxScale = 0.203
    },
    [5] = {
        Id = 5,
        Pos = Vector3(-45.877636, -5.873641, 30.218491),
        Rot = EulerDegree(-0.000000, -25.173138, -0.000000),
        MinScale = 0.28,
        MaxScale = 0.197
    },
    [6] = {
        Id = 6,
        Pos = Vector3(-42.441597, -5.800157, 24.485994),
        Rot = EulerDegree(-0.000000, -25.173138, -0.000000),
        MinScale = 0.32,
        MaxScale = 0.196
    },
    [7] = {
        Id = 7,
        Pos = Vector3(-58.598560, -6.027812, 32.676758),
        Rot = EulerDegree(-0.000000, -25.173138, -0.000000),
        MinScale = 0.33,
        MaxScale = 0.202
    },
    [8] = {
        Id = 8,
        Pos = Vector3(-54.351234, -5.873641, 37.728607),
        Rot = EulerDegree(-0.000000, -25.173138, -0.000000),
        MinScale = 0.28,
        MaxScale = 0.214
    },
    [9] = {
        Id = 9,
        Pos = Vector3(-50.915192, -5.800157, 31.996109),
        Rot = EulerDegree(-0.000000, -25.173138, -0.000000),
        MinScale = 0.31,
        MaxScale = 0.214
    },
    [10] = {
        Id = 10,
        Pos = Vector3(-51.877731, -6.027812, 36.187668),
        Rot = EulerDegree(-0.000000, -25.173138, -0.000000),
        MinScale = 0.28,
        MaxScale = 0.241
    },
    [11] = {
        Id = 11,
        Pos = Vector3(-47.630405, -5.873641, 41.239517),
        Rot = EulerDegree(-0.000000, -25.173138, -0.000000),
        MinScale = 0.29,
        MaxScale = 0.249
    },
    [12] = {
        Id = 12,
        Pos = Vector3(-44.194366, -5.800157, 35.507019),
        Rot = EulerDegree(-0.000000, -25.173138, -0.000000),
        MinScale = 0.27,
        MaxScale = 0.236
    },
    [13] = {
        Id = 13,
        Pos = Vector3(-64.395912, -6.051762, 35.727791),
        Rot = EulerDegree(-0.000000, -25.173124, -0.000000),
        MinScale = 0.35,
        MaxScale = 0.285
    },
    [14] = {
        Id = 14,
        Pos = Vector3(-59.254887, -5.865151, 41.842609),
        Rot = EulerDegree(-0.000000, -25.173124, -0.000000),
        MinScale = 0.31,
        MaxScale = 0.238
    },
    [15] = {
        Id = 15,
        Pos = Vector3(-55.095863, -5.776206, 34.903927),
        Rot = EulerDegree(-0.000000, -25.173124, -0.000000),
        MinScale = 0.32,
        MaxScale = 0.231
    },
    [16] = {
        Id = 16,
        Pos = Vector3(-64.395905, -6.051762, 20.852243),
        Rot = EulerDegree(-0.000000, -25.173124, -0.000000),
        MinScale = 0.31,
        MaxScale = 0.284
    },
    [17] = {
        Id = 17,
        Pos = Vector3(-59.254887, -5.865151, 26.967062),
        Rot = EulerDegree(-0.000000, -25.173124, -0.000000),
        MinScale = 0.37,
        MaxScale = 0.247
    },
    [18] = {
        Id = 18,
        Pos = Vector3(-55.095863, -5.776206, 20.028381),
        Rot = EulerDegree(-0.000000, -25.173124, -0.000000),
        MinScale = 0.33,
        MaxScale = 0.271
    },
    [19] = {
        Id = 19,
        Pos = Vector3(-56.879066, -6.051762, 22.427950),
        Rot = EulerDegree(-0.000000, -25.173124, -0.000000),
        MinScale = 0.36,
        MaxScale = 0.287
    },
    [20] = {
        Id = 20,
        Pos = Vector3(-51.738049, -5.865151, 28.542768),
        Rot = EulerDegree(-0.000000, -25.173124, -0.000000),
        MinScale = 0.34,
        MaxScale = 0.296
    },
    [21] = {
        Id = 21,
        Pos = Vector3(-47.579025, -5.776206, 21.604084),
        Rot = EulerDegree(-0.000000, -25.173124, -0.000000),
        MinScale = 0.34,
        MaxScale = 0.262
    },
    [22] = {
        Id = 22,
        Pos = Vector3(-56.879066, -6.051762, 6.172745),
        Rot = EulerDegree(-0.000000, -25.173124, -0.000000),
        MinScale = 0.33,
        MaxScale = 0.283
    },
    [23] = {
        Id = 23,
        Pos = Vector3(-51.738049, -5.865151, 12.287563),
        Rot = EulerDegree(-0.000000, -25.173124, -0.000000),
        MinScale = 0.31,
        MaxScale = 0.251
    },
    [24] = {
        Id = 24,
        Pos = Vector3(-47.579025, -5.776206, 5.348881),
        Rot = EulerDegree(-0.000000, -25.173124, -0.000000),
        MinScale = 0.4,
        MaxScale = 0.296
    },
    [25] = {
        Id = 25,
        Pos = Vector3(-47.628365, -6.051762, 14.637194),
        Rot = EulerDegree(-0.000000, -25.173124, -0.000000),
        MinScale = 0.38,
        MaxScale = 0.24
    },
    [26] = {
        Id = 26,
        Pos = Vector3(-42.487347, -5.865151, 20.752012),
        Rot = EulerDegree(-0.000000, -25.173124, -0.000000),
        MinScale = 0.38,
        MaxScale = 0.282
    },
    [27] = {
        Id = 27,
        Pos = Vector3(-38.328323, -5.776206, 13.813328),
        Rot = EulerDegree(-0.000000, -25.173124, -0.000000),
        MinScale = 0.37,
        MaxScale = 0.287
    },
    [28] = {
        Id = 28,
        Pos = Vector3(-69.802155, -6.051762, 19.402744),
        Rot = EulerDegree(-0.000000, -25.173124, -0.000000),
        MinScale = 0.32,
        MaxScale = 0.228
    },
    [29] = {
        Id = 29,
        Pos = Vector3(-64.661140, -5.865151, 25.517561),
        Rot = EulerDegree(-0.000000, -25.173124, -0.000000),
        MinScale = 0.31,
        MaxScale = 0.257
    },
    [30] = {
        Id = 30,
        Pos = Vector3(-60.502117, -5.776206, 18.578876),
        Rot = EulerDegree(-0.000000, -25.173124, -0.000000),
        MinScale = 0.33,
        MaxScale = 0.243
    },
    [31] = {
        Id = 31,
        Pos = Vector3(-72.611214, -6.051762, 33.686977),
        Rot = EulerDegree(-0.000000, -25.173124, -0.000000),
        MinScale = 0.33,
        MaxScale = 0.27
    },
    [32] = {
        Id = 32,
        Pos = Vector3(-67.470207, -5.865151, 39.801796),
        Rot = EulerDegree(-0.000000, -25.173124, -0.000000),
        MinScale = 0.34,
        MaxScale = 0.245
    },
    [33] = {
        Id = 33,
        Pos = Vector3(-63.311176, -5.776206, 32.863113),
        Rot = EulerDegree(-0.000000, -25.173124, -0.000000),
        MinScale = 0.35,
        MaxScale = 0.239
    }
}

return LotusLocateInfoXls
