--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//GameChair.xlsx

local ChairGlobalConfigXls = {
    SpiritDecayRate = {
        Key = 'SpiritDecayRate',
        Value = {[23]=0.2,[20]=0.18,[15]=0.12,[10]=0.1,[5]=0.08,[0]=0.05}
    },
    SpiritIncrease = {
        Key = 'SpiritIncrease',
        Value = 0.01
    }
}

return ChairGlobalConfigXls
