--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: .//ItemNew.xlsm

local BowXls = {
    [2001] = {
        ItemID = 2001,
        ModelName = 'Arch_Wood',
        ParentNode = 'Bone_L_Hand.LHandWeaponNode',
        Offset = Vector3(0, 0, 0),
        Angle = EulerDegree(0, -30, 0),
        ChargeTime = 0.5,
        ProjectileID = 2,
        ProjectileCount = 1,
        ProjectileSpeed = 40.0,
        ChargeEffect = 'BowChangeEffect',
        ShootSoundID = 56,
        ShootEffect = 'BowReleaseEffect'
    },
    [2002] = {
        ItemID = 2002,
        ModelName = 'S_Slingshot_Yellow_01',
        ParentNode = 'Bone_L_Hand.LHandWeaponNode',
        Offset = Vector3(0, 0, 0),
        Angle = EulerDegree(0, -30, 0),
        ChargeTime = 0.5,
        ProjectileID = 3,
        ProjectileCount = 1,
        ProjectileSpeed = 40.0,
        ChargeEffect = 'BowChangeEffect',
        ShootSoundID = 56,
        ShootEffect = 'BowReleaseEffect'
    },
    [2003] = {
        ItemID = 2003,
        ModelName = 'S_Arch_Wood_01',
        ParentNode = 'Bone_L_Hand.LHandWeaponNode',
        Offset = Vector3(0, 0, 0),
        Angle = EulerDegree(0, -30, 0),
        ChargeTime = 0.5,
        ProjectileID = 1,
        ProjectileCount = 1,
        ProjectileSpeed = 40.0,
        ChargeEffect = 'BowChangeEffect',
        ShootSoundID = 56,
        ShootEffect = 'BowReleaseEffect'
    },
    [2004] = {
        ItemID = 2004,
        ModelName = 'LifeBow',
        ParentNode = 'Bone_L_Hand.LHandWeaponNode',
        Offset = Vector3(0, 0, 0),
        Angle = EulerDegree(0, -30, 0),
        ChargeTime = 0.5,
        ProjectileID = 4,
        ProjectileCount = 1,
        ProjectileSpeed = 40.0,
        ChargeEffect = 'LifeBowChangeEffect',
        ShootSoundID = 56,
        ShootEffect = 'LifeBowFire'
    },
    [2005] = {
        ItemID = 2005,
        ModelName = 'LightingBow',
        ParentNode = 'Bone_L_Hand.LHandWeaponNode',
        Offset = Vector3(0, 0, 0),
        Angle = EulerDegree(0, -30, 0),
        ChargeTime = 0.5,
        ProjectileID = 5,
        ProjectileCount = 1,
        ProjectileSpeed = 40.0,
        ChargeEffect = 'LightingBowChangeEffect',
        ShootSoundID = 56,
        ShootEffect = 'LightingBowFire'
    },
    [2006] = {
        ItemID = 2006,
        ModelName = 'DarkBow',
        ParentNode = 'Bone_L_Hand.LHandWeaponNode',
        Offset = Vector3(0, 0, 0),
        Angle = EulerDegree(0, -30, 0),
        ChargeTime = 0.5,
        ProjectileID = 6,
        ProjectileCount = 1,
        ProjectileSpeed = 40.0,
        ChargeEffect = 'BowChangeEffect',
        ShootSoundID = 56,
        ShootEffect = 'DarkBowFire'
    },
    [2007] = {
        ItemID = 2007,
        ModelName = 'FireBow',
        ParentNode = 'Bone_L_Hand.LHandWeaponNode',
        Offset = Vector3(0, 0, 0),
        Angle = EulerDegree(0, -30, 0),
        ChargeTime = 0.5,
        ProjectileID = 7,
        ProjectileCount = 1,
        ProjectileSpeed = 40.0,
        ChargeEffect = 'FireBowChangeEffect',
        ShootSoundID = 56,
        ShootEffect = 'FireBowFire'
    }
}

return BowXls
