--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//ItemNew.xlsx

local TaskXls = {
    [6001] = {
        ItemID = 6001,
        TaskDes = '',
        Npc = {14},
        RewardItem = 0,
        RewardGold = 50,
        NpcText = 'Task_NpcText_6001'
    },
    [6002] = {
        ItemID = 6002,
        TaskDes = '',
        Npc = {13},
        RewardItem = 0,
        RewardGold = 50,
        NpcText = 'Task_NpcText_6002'
    },
    [6003] = {
        ItemID = 6003,
        TaskDes = '',
        Npc = {3},
        RewardItem = 0,
        RewardGold = 50,
        NpcText = 'Task_NpcText_6003'
    },
    [6004] = {
        ItemID = 6004,
        TaskDes = '',
        Npc = {5},
        RewardItem = 0,
        RewardGold = 50,
        NpcText = 'Task_NpcText_6004'
    },
    [6005] = {
        ItemID = 6005,
        TaskDes = '',
        Npc = {6},
        RewardItem = 0,
        RewardGold = 50,
        NpcText = 'Task_NpcText_6005'
    },
    [6006] = {
        ItemID = 6006,
        TaskDes = '',
        Npc = {12},
        RewardItem = 0,
        RewardGold = 200,
        NpcText = 'Task_NpcText_6006'
    },
    [6007] = {
        ItemID = 6007,
        TaskDes = '',
        Npc = {3},
        RewardItem = 0,
        RewardGold = 200,
        NpcText = 'Task_NpcText_6007'
    }
}

return TaskXls
