--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//GameHunting.xlsx

local AnimalInfoXls = {
    [1] = {
        Id = 1,
        Name = 'pig',
        Model = 'pig',
        ItemId = 1.0,
        Weight = 40
    },
    [2] = {
        Id = 2,
        Name = 'deer',
        Model = 'deer',
        ItemId = 1.0,
        Weight = 60
    },
    [3] = {
        Id = 3,
        Name = 'rabbit',
        Model = 'rabbit',
        ItemId = 1.0,
        Weight = 80
    },
    [4] = {
        Id = 4,
        Name = 'tiger',
        Model = 'tiger',
        ItemId = 1.0,
        Weight = 5
    },
    [5] = {
        Id = 5,
        Name = 'bird',
        Model = 'bird',
        ItemId = 1.0,
        Weight = 20
    },
    [6] = {
        Id = 6,
        Name = 'chicken',
        Model = 'chicken',
        ItemId = 1.0,
        Weight = 100
    }
}

return AnimalInfoXls
