--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//Item.xlsm

local TaskItemXls = {
    [5001] = {
        ItemID = 5001,
        Npc = nil,
        RewardItem = nil,
        RewardGold = 200,
        NpcText = 'TaskItem_NpcText_5001'
    }
}

return TaskItemXls
