--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//Item.xlsm

local PickItemXls = {
    [1] = {
        ID = 1,
        Archetype = '暴怒的大魔王',
        Type = 2,
        ItemId = 2001,
        LifeTime = 60,
        Durability = -1
    }
}

return PickItemXls
