--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//GuitarPitch.xlsx

local GuitarPitchXls = {
    [1] = {
        StringID = 1,
        Pitch = {[0]=91,[1]=92,[2]=93,[3]=94,[4]=95,[5]=96}
    },
    [2] = {
        StringID = 2,
        Pitch = {[0]=86,[1]=87,[2]=88,[3]=89,[4]=90,[5]=91}
    },
    [3] = {
        StringID = 3,
        Pitch = {[0]=82,[1]=83,[2]=84,[3]=85,[4]=86,[5]=87}
    },
    [4] = {
        StringID = 4,
        Pitch = {[0]=77,[1]=78,[2]=79,[3]=80,[4]=81,[5]=82}
    },
    [5] = {
        StringID = 5,
        Pitch = {[0]=72,[1]=73,[2]=74,[3]=75,[4]=76,[5]=77}
    },
    [6] = {
        StringID = 6,
        Pitch = {[0]=67,[1]=68,[2]=69,[3]=70,[4]=71,[5]=72}
    }
}

return GuitarPitchXls
