--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//GameChair.xlsx

local ChairGlobalConfigXls = {
    FlyingTime = {
        Key = 'FlyingTime',
        Value = 3.0
    },
    FlyingSpeed = {
        Key = 'FlyingSpeed',
        Value = 5.0
    },
    NormalAngularVelocity = {
        Key = 'NormalAngularVelocity',
        Value = Vector3(0.5,0,0)
    },
    NormalMaxAngle = {
        Key = 'NormalMaxAngle',
        Value = 15.0
    },
    NormalMinAngle = {
        Key = 'NormalMinAngle',
        Value = -15.0
    },
    BoostAngularVelocity = {
        Key = 'BoostAngularVelocity',
        Value = Vector3(1,0,0)
    }
}

return ChairGlobalConfigXls
