--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: .//Global_Config.xls

local GlobalConfigXls = {
    DefaultLanguage = "CHS",
    GameMaxNum = 12.0,
    GameMinNum = 1.0,
    WorldTable = "G_Table_Wood_World",
    LocalDefaultTable = "G_Table_Wood_Default",
    LocalTableOffset = Vector3(0, 4.3, 0)
}

return GlobalConfigXls
