--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//Item.xlsm

local LongRangeWeaponXls = {
    [2001] = {
        ItemID = 2001,
        AttackAnimName = {'BowAttack'},
        ModelName = 'M_Arrow',
        ArrowModelName = 'Arrow_01',
        AttckCD = 1.0,
        ParentNode = 'Bone_L_Hand.LHandWeaponNode',
        Offset = Vector3(0, 0, 0),
        Angle = EulerDegree(45, 0, 0),
        HealthChange = 20,
        ExplosionRange = 0.0,
        UseAddBuffDur = -1.0,
        UseAddBuffID = 3,
        HitAddBuffID = 1,
        HitAddBuffDur = 5.0,
        HitRemoveBuffID = 0,
        HitEffectName = '0.0',
        HitSoundID = '0.0',
        Hunt = true,
        Mole = false
    },
    [2002] = {
        ItemID = 2002,
        AttackAnimName = {'BowAttack'},
        ModelName = 'G_Arch_Wood_01',
        ArrowModelName = 'G_Arrow_Wood_01',
        AttckCD = 1.0,
        ParentNode = 'Bone_L_Hand.LHandWeaponNode',
        Offset = Vector3(0, 0, 0),
        Angle = EulerDegree(45, 0, 0),
        HealthChange = 10,
        ExplosionRange = 2.0,
        UseAddBuffDur = -1.0,
        UseAddBuffID = 3,
        HitAddBuffID = 0,
        HitAddBuffDur = 0.0,
        HitRemoveBuffID = 0,
        HitEffectName = '0.0',
        HitSoundID = '0.0',
        Hunt = true,
        Mole = false
    },
    [2003] = {
        ItemID = 2003,
        AttackAnimName = {'BowAttack'},
        ModelName = 'G_Slingshot_Yellow_01',
        ArrowModelName = 'M_Slingshot',
        AttckCD = 1.0,
        ParentNode = 'Bone_L_Hand.LHandWeaponNode',
        Offset = Vector3(0, 0, 0),
        Angle = EulerDegree(0, 0, 0),
        HealthChange = 10,
        ExplosionRange = 0.0,
        UseAddBuffDur = -1.0,
        UseAddBuffID = 3,
        HitAddBuffID = 0,
        HitAddBuffDur = 0.0,
        HitRemoveBuffID = 0,
        HitEffectName = '0.0',
        HitSoundID = '0.0',
        Hunt = true,
        Mole = false
    }
}

return LongRangeWeaponXls
