--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//GameHunting.xlsm

local AnimalAreaXls = {
    [1] = {
        ID = 1,
        Pos = Vector3(-81.512703, -7.180514, 6.452000),
        Range = 20.0,
        AmountMax = 5,
        InitAmount = 10,
        SpawnPoint = {{Vector3(-89.387802,-7.180514,6.452000),EulerDegree(0.000000,0.000000,0.000000)},{Vector3(-81.512703,-7.180514,19.455215),EulerDegree(0.000000,0.000000,0.000000)},{Vector3(-71.973419,-7.180514,4.556374),EulerDegree(0.000000,0.000000,0.000000)}},
        AnimalIDList = {1, 2, 3, 5, 6, 7, 8}
    },
    [2] = {
        ID = 2,
        Pos = Vector3(-118.971001, -9.663149, 57.034100),
        Range = 14.0,
        AmountMax = 4,
        InitAmount = 10,
        SpawnPoint = {{Vector3(-122.865410,-9.663149,57.034100),EulerDegree(0.000000,0.000000,0.000000)},{Vector3(-118.971001,-9.663149,60.286625),EulerDegree(0.000000,0.000000,0.000000)},{Vector3(-117.318825,-9.663149,55.138474),EulerDegree(0.000000,0.000000,0.000000)}},
        AnimalIDList = {1, 2, 3, 5, 6, 7, 8}
    },
    [3] = {
        ID = 3,
        Pos = Vector3(-140.350082, -2.074387, 103.874001),
        Range = 17.5,
        AmountMax = 4,
        InitAmount = 10,
        SpawnPoint = {{Vector3(-144.244492,-2.074387,103.874001),EulerDegree(0.000000,0.000000,0.000000)},{Vector3(-140.350082,-2.074387,107.126526),EulerDegree(0.000000,0.000000,0.000000)},{Vector3(-138.697906,-2.074387,101.978378),EulerDegree(0.000000,0.000000,0.000000)}},
        AnimalIDList = {1, 2, 3, 5, 6, 7, 8}
    },
    [4] = {
        ID = 4,
        Pos = Vector3(-63.085899, 11.784500, 91.367302),
        Range = 15.0,
        AmountMax = 5,
        InitAmount = 10,
        SpawnPoint = {{Vector3(-66.980309,11.784500,91.367302),EulerDegree(0.000000,0.000000,0.000000)},{Vector3(-63.085899,11.784500,94.619827),EulerDegree(0.000000,0.000000,0.000000)},{Vector3(-61.433723,11.784500,89.471680),EulerDegree(0.000000,0.000000,0.000000)}},
        AnimalIDList = {1, 2, 3, 5, 6, 7, 8}
    },
    [5] = {
        ID = 5,
        Pos = Vector3(-110.724800, -2.885900, 24.118401),
        Range = 9.0,
        AmountMax = 4,
        InitAmount = 10,
        SpawnPoint = {{Vector3(-114.619194,-2.885900,24.118401),EulerDegree(7.474659,0.000000,0.000000)},{Vector3(-110.724800,-3.309012,27.343277),EulerDegree(7.474659,0.000000,0.000000)},{Vector3(-109.072632,-2.639303,22.238888),EulerDegree(7.474659,0.000000,0.000000)}},
        AnimalIDList = {1, 2, 3, 5, 6, 7, 8}
    }
}

return AnimalAreaXls
