--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: ./Table/Game.xls

local PlayerAniXls = {
    [1000] = {
        ID = 1000,
        Select = 'BallEquip',
        CancelSelect = 'Drop',
        Hand = 'PressButton',
        OutHand = 'AttackPunch1',
        Rand = {"OpenDoor", "PushDoor", "Dined"}
    },
    [1001] = {
        ID = 1001,
        Select = 'BallEquip',
        CancelSelect = 'Drop',
        Hand = 'PressButton',
        OutHand = 'AttackPunch2',
        Rand = {"OpenDoor", "PushDoor", "Dined"}
    },
    [1002] = {
        ID = 1002,
        Select = 'BallEquip',
        CancelSelect = 'Drop',
        Hand = 'PressButton',
        OutHand = 'AttackPunch2',
        Rand = {"OpenDoor", "PushDoor", "Dined"}
    }
}

return PlayerAniXls
