--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//ItemConfig.xlsx

local BuffXls = {
    [1] = {
        ID = 1,
        BuffCoverIDList = {0},
        AvatarHeightSize_Overlay = 1.0,
        AvatarHeadSize_Overlay = 1.0,
        AvatarWidth_Overlay = 1.0,
        HeadEffect_Overlay = 'Fire',
        BodyEffect_Overlay = 'Fire',
        FootEffect_Overlay = 'Fire',
        WalkSpeed_Overlay = 1.0,
        JumpUpVelocity_Overlay = 1.0,
        GravityScale_Overlay = 1.0,
        SkinID_Cover = 1,
        AnimState_Cover = 'nil',
        EnableEquipable_Cover = true
    }
}

return BuffXls
