--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//ItemNew.xlsx

local ProjectileXls = {
    [1] = {
        ProjectileID = 1,
        Name = '木箭',
        ModelName = 'Arrow_Wood_01',
        HealthChange = 0,
        HitRange = 0.0,
        HitForce = 0.0,
        HitType = 1,
        HitAddBuffID = 0,
        HitAddBuffDur = 0.0,
        HitRemoveBuffID = 0,
        HitEffectName = 'ArrowTartgetHitEffect',
        HitSoundID = '33.0',
        Hunt = true
    },
    [2] = {
        ProjectileID = 2,
        Name = '子弹',
        ModelName = 'Arrow_Wood_01',
        HealthChange = 0,
        HitRange = 0.0,
        HitForce = 0.0,
        HitType = 1,
        HitAddBuffID = 0,
        HitAddBuffDur = 0.0,
        HitRemoveBuffID = 0,
        HitEffectName = 'ArrowTartgetHitEffect',
        HitSoundID = '33.0',
        Hunt = true
    }
}

return ProjectileXls
