--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//Cook.xlsx

local CookUIConfigXls = {
    [1] = {
        ID = 1,
        Name = 7001
    },
    [2] = {
        ID = 2,
        Name = 7002
    },
    [3] = {
        ID = 3,
        Name = 7003
    },
    [4] = {
        ID = 4,
        Name = 7004
    },
    [5] = {
        ID = 5,
        Name = 7005
    },
    [6] = {
        ID = 6,
        Name = 7006
    },
    [7] = {
        ID = 7,
        Name = 7007
    },
    [8] = {
        ID = 8,
        Name = 7008
    },
    [9] = {
        ID = 9,
        Name = 7009
    }
}

return CookUIConfigXls
