--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: .//ItemNew.xlsm

local PistolXls = {
    [3001] = {
        ItemID = 3001,
        ModelName = 'Pistol',
        ParentNode = 'Bone_R_Hand.RHandWeaponNode',
        Offset = Vector3(0, 0, 0),
        Angle = EulerDegree(0, 0, 0),
        FireRate = 0.5,
        ProjectileID = 2,
        ProjectileCount = 1,
        ProjectileSpeed = 50.0,
        ShootSoundID = 56,
        ShootEffect = 'BowReleaseEffect'
    }
}

return PistolXls
