--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: .//GuiText.xlsx

local GuiTextXls = {
    InfoGui_1 = {
        TextId = 'InfoGui_1',
        Txt = 'GuiText_Txt_InfoGui_1'
    },
    InfoGui_2 = {
        TextId = 'InfoGui_2',
        Txt = 'GuiText_Txt_InfoGui_2'
    },
    InfoGui_3 = {
        TextId = 'InfoGui_3',
        Txt = 'GuiText_Txt_InfoGui_3'
    },
    InfoGui_4 = {
        TextId = 'InfoGui_4',
        Txt = 'GuiText_Txt_InfoGui_4'
    },
    InfoGui_5 = {
        TextId = 'InfoGui_5',
        Txt = 'GuiText_Txt_InfoGui_5'
    },
    SnailGui_1 = {
        TextId = 'SnailGui_1',
        Txt = 'GuiText_Txt_SnailGui_1'
    },
    SnailGui_2 = {
        TextId = 'SnailGui_2',
        Txt = 'GuiText_Txt_SnailGui_2'
    },
    SnailGui_3 = {
        TextId = 'SnailGui_3',
        Txt = 'GuiText_Txt_SnailGui_3'
    },
    SnailGui_4 = {
        TextId = 'SnailGui_4',
        Txt = 'GuiText_Txt_SnailGui_4'
    },
    SnailGui_5 = {
        TextId = 'SnailGui_5',
        Txt = 'GuiText_Txt_SnailGui_5'
    },
    SnailGui_6 = {
        TextId = 'SnailGui_6',
        Txt = 'GuiText_Txt_SnailGui_6'
    },
    SnailGui_7 = {
        TextId = 'SnailGui_7',
        Txt = 'GuiText_Txt_SnailGui_7'
    },
    SnailGui_8 = {
        TextId = 'SnailGui_8',
        Txt = 'GuiText_Txt_SnailGui_8'
    },
    SnailGui_9 = {
        TextId = 'SnailGui_9',
        Txt = 'GuiText_Txt_SnailGui_9'
    },
    SnailGui_10 = {
        TextId = 'SnailGui_10',
        Txt = 'GuiText_Txt_SnailGui_10'
    },
    SnailGui_11 = {
        TextId = 'SnailGui_11',
        Txt = 'GuiText_Txt_SnailGui_11'
    },
    SnailGui_12 = {
        TextId = 'SnailGui_12',
        Txt = 'GuiText_Txt_SnailGui_12'
    },
    SnailGui_13 = {
        TextId = 'SnailGui_13',
        Txt = 'GuiText_Txt_SnailGui_13'
    },
    SnailGui_14 = {
        TextId = 'SnailGui_14',
        Txt = 'GuiText_Txt_SnailGui_14'
    },
    SnailGui_15 = {
        TextId = 'SnailGui_15',
        Txt = 'GuiText_Txt_SnailGui_15'
    },
    SnailGui_16 = {
        TextId = 'SnailGui_16',
        Txt = 'GuiText_Txt_SnailGui_16'
    },
    PetGui_1 = {
        TextId = 'PetGui_1',
        Txt = 'GuiText_Txt_PetGui_1'
    },
    PetGui_2 = {
        TextId = 'PetGui_2',
        Txt = 'GuiText_Txt_PetGui_2'
    },
    PetGui_3 = {
        TextId = 'PetGui_3',
        Txt = 'GuiText_Txt_PetGui_3'
    },
    PetGui_4 = {
        TextId = 'PetGui_4',
        Txt = 'GuiText_Txt_PetGui_4'
    },
    PetGui_5 = {
        TextId = 'PetGui_5',
        Txt = 'GuiText_Txt_PetGui_5'
    },
    PetGui_6 = {
        TextId = 'PetGui_6',
        Txt = 'GuiText_Txt_PetGui_6'
    },
    PetGui_7 = {
        TextId = 'PetGui_7',
        Txt = 'GuiText_Txt_PetGui_7'
    },
    MoleGui_1 = {
        TextId = 'MoleGui_1',
        Txt = 'GuiText_Txt_MoleGui_1'
    },
    ShopGui_1 = {
        TextId = 'ShopGui_1',
        Txt = 'GuiText_Txt_ShopGui_1'
    },
    ShopGui_2 = {
        TextId = 'ShopGui_2',
        Txt = 'GuiText_Txt_ShopGui_2'
    },
    ShopGui_3 = {
        TextId = 'ShopGui_3',
        Txt = 'GuiText_Txt_ShopGui_3'
    },
    ShopGui_4 = {
        TextId = 'ShopGui_4',
        Txt = 'GuiText_Txt_ShopGui_4'
    },
    NpcGui_1 = {
        TextId = 'NpcGui_1',
        Txt = 'GuiText_Txt_NpcGui_1'
    },
    NpcGui_2 = {
        TextId = 'NpcGui_2',
        Txt = 'GuiText_Txt_NpcGui_2'
    },
    NpcGui_3 = {
        TextId = 'NpcGui_3',
        Txt = 'GuiText_Txt_NpcGui_3'
    },
    CookGui_1 = {
        TextId = 'CookGui_1',
        Txt = 'GuiText_Txt_CookGui_1'
    },
    CookGui_2 = {
        TextId = 'CookGui_2',
        Txt = 'GuiText_Txt_CookGui_2'
    },
    CookGui_3 = {
        TextId = 'CookGui_3',
        Txt = 'GuiText_Txt_CookGui_3'
    },
    CookGui_4 = {
        TextId = 'CookGui_4',
        Txt = 'GuiText_Txt_CookGui_4'
    },
    CookGui_5 = {
        TextId = 'CookGui_5',
        Txt = 'GuiText_Txt_CookGui_5'
    },
    CookGui_6 = {
        TextId = 'CookGui_6',
        Txt = 'GuiText_Txt_CookGui_6'
    },
    CookGui_7 = {
        TextId = 'CookGui_7',
        Txt = 'GuiText_Txt_CookGui_7'
    },
    CookGui_8 = {
        TextId = 'CookGui_8',
        Txt = 'GuiText_Txt_CookGui_8'
    },
    CookGui_9 = {
        TextId = 'CookGui_9',
        Txt = 'GuiText_Txt_CookGui_9'
    }
}

return GuiTextXls
