--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//Shop.xlsx

local ShopXls = {
    [2] = {
        [2001] = {
            NpcId = 2,
            Index = 1,
            ItemId = 2001,
            Price = 300
        },
        [2002] = {
            NpcId = 2,
            Index = 2,
            ItemId = 2002,
            Price = 1500
        },
        [2003] = {
            NpcId = 2,
            Index = 3,
            ItemId = 2003,
            Price = 2500
        },
        [2005] = {
            NpcId = 2,
            Index = 4,
            ItemId = 2005,
            Price = 10000
        },
        [4002] = {
            NpcId = 2,
            Index = 5,
            ItemId = 4002,
            Price = 500
        },
        [4003] = {
            NpcId = 2,
            Index = 6,
            ItemId = 4003,
            Price = 1500
        }
    },
    [5] = {
        [1023] = {
            NpcId = 5,
            Index = 1,
            ItemId = 1023,
            Price = 1000
        },
        [1034] = {
            NpcId = 5,
            Index = 2,
            ItemId = 1034,
            Price = 1000
        },
        [1035] = {
            NpcId = 5,
            Index = 3,
            ItemId = 1035,
            Price = 1000
        },
        [1036] = {
            NpcId = 5,
            Index = 4,
            ItemId = 1036,
            Price = 1000
        },
        [1037] = {
            NpcId = 5,
            Index = 5,
            ItemId = 1037,
            Price = 1000
        },
        [1038] = {
            NpcId = 5,
            Index = 6,
            ItemId = 1038,
            Price = 1000
        }
    },
    [10] = {
        [1013] = {
            NpcId = 10,
            Index = 1,
            ItemId = 1013,
            Price = 10000
        },
        [1014] = {
            NpcId = 10,
            Index = 2,
            ItemId = 1014,
            Price = 10000
        }
    },
    [11] = {
        [1003] = {
            NpcId = 11,
            Index = 1,
            ItemId = 1003,
            Price = 2500
        },
        [1005] = {
            NpcId = 11,
            Index = 2,
            ItemId = 1005,
            Price = 800
        },
        [1006] = {
            NpcId = 11,
            Index = 3,
            ItemId = 1006,
            Price = 1200
        },
        [1007] = {
            NpcId = 11,
            Index = 4,
            ItemId = 1007,
            Price = 800
        },
        [1009] = {
            NpcId = 11,
            Index = 5,
            ItemId = 1009,
            Price = 1200
        },
        [1011] = {
            NpcId = 11,
            Index = 6,
            ItemId = 1011,
            Price = 800
        },
        [1010] = {
            NpcId = 11,
            Index = 7,
            ItemId = 1010,
            Price = 1000
        }
    },
    [12] = {
        [1015] = {
            NpcId = 12,
            Index = 1,
            ItemId = 1015,
            Price = 2500
        },
        [1016] = {
            NpcId = 12,
            Index = 2,
            ItemId = 1016,
            Price = 800
        },
        [1012] = {
            NpcId = 12,
            Index = 3,
            ItemId = 1012,
            Price = 500
        }
    }
}

return ShopXls
