--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//SoundConfig.xlsx

local SoundXls = {
    [1] = {
        ID = 1,
        Type = 'SoundEffect',
        Name = 'Clap',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Clap',
        Info = ''
    },
    [2] = {
        ID = 2,
        Type = 'BGM',
        Name = 'BGM',
        IsLoop = false,
        Volume = 45.0,
        Path = 'Audio/Temp_BGM',
        Info = ''
    },
    [3] = {
        ID = 3,
        Type = 'SoundEffect',
        Name = 'Sfx_Shop_1s_Open',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Sfx_Shop_1s_Open',
        Info = '对话弹出'
    },
    [4] = {
        ID = 4,
        Type = 'SoundEffect',
        Name = 'Coin_Slide_Carpet',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Coin_Slide_Carpet',
        Info = '吃金币的音效'
    },
    [5] = {
        ID = 5,
        Type = 'SoundEffect',
        Name = 'Sfx_Shop_1s_Open',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Sfx_Shop_1s_Open',
        Info = '界面弹出（支付）'
    },
    [6] = {
        ID = 6,
        Type = 'SoundEffect',
        Name = 'Sfx_Shop_1s_Close',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Sfx_Shop_1s_Close',
        Info = '界面关闭（支付）'
    },
    [7] = {
        ID = 7,
        Type = 'SoundEffect',
        Name = 'Sfx_Diamond_1s_Add',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Sfx_Diamond_1s_Add',
        Info = '点击确认（支付）'
    },
    [8] = {
        ID = 8,
        Type = 'SoundEffect',
        Name = 'Sfx_Shop_1s_BuyConfirm',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Sfx_Shop_1s_BuyConfirm',
        Info = '下注成功'
    },
    [9] = {
        ID = 9,
        Type = 'SoundEffect',
        Name = '',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/',
        Info = '赛前预备'
    },
    [10] = {
        ID = 10,
        Type = 'SoundEffect',
        Name = 'Sfx_Shop_1s_Open',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Sfx_Shop_1s_Open',
        Info = '起跑'
    },
    [11] = {
        ID = 11,
        Type = 'SoundEffect',
        Name = 'Drone_attack_Money_shoot',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Drone_attack_Money_shoot',
        Info = '赢到钱'
    },
    [12] = {
        ID = 12,
        Type = 'SoundEffect',
        Name = 'Sfx_Shop_1s_Open',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Sfx_Shop_1s_Open',
        Info = '输了钱'
    },
    [13] = {
        ID = 13,
        Type = 'SoundEffect',
        Name = 'Success',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Success',
        Info = '成功捕捉'
    },
    [14] = {
        ID = 14,
        Type = 'SoundEffect',
        Name = 'Sit',
        IsLoop = false,
        Volume = 35.0,
        Path = 'Audio/Sit',
        Info = '坐下的音效'
    },
    [15] = {
        ID = 15,
        Type = 'SoundEffect',
        Name = 'DOORS_WOOD_GATE_OPEN_2',
        IsLoop = true,
        Volume = 20.0,
        Path = 'Audio/DOORS_WOOD_GATE_OPEN_2',
        Info = '摇木马的咯吱声'
    },
    [16] = {
        ID = 16,
        Type = 'SoundEffect',
        Name = 'TempBGM',
        IsLoop = true,
        Volume = 60.0,
        Path = 'Audio/TempBGM',
        Info = '鸟语（环境）'
    },
    [17] = {
        ID = 17,
        Type = 'SoundEffect',
        Name = 'Footstep_deck-002',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Footstep_deck-002',
        Info = '脚步声'
    },
    [18] = {
        ID = 18,
        Type = 'SoundEffect',
        Name = 'PlayerControlModule_Jump_Deck',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/PlayerControlModule_Jump_Deck',
        Info = '跳落地'
    },
    [19] = {
        ID = 19,
        Type = 'SoundEffect',
        Name = 'JumpIntoWater',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/JumpIntoWater',
        Info = '进入水中的声音'
    },
    [20] = {
        ID = 20,
        Type = 'SoundEffect',
        Name = 'WaterWalking',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/WaterWalking',
        Info = '在水中的脚步声'
    },
    [21] = {
        ID = 21,
        Type = 'SoundEffect',
        Name = 'AudioScript_Swim_03',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/AudioScript_Swim_03',
        Info = '游泳移动的声音'
    },
    [22] = {
        ID = 22,
        Type = 'SoundEffect',
        Name = 'DrinkBuff_Skywalker_Jump',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/DrinkBuff_Skywalker_Jump',
        Info = '踩蘑菇'
    },
    [23] = {
        ID = 23,
        Type = 'SoundEffect',
        Name = 'Marquis_ClothChange',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Marquis_ClothChange',
        Info = '换外观的交互声音'
    },
    [24] = {
        ID = 24,
        Type = 'SoundEffect',
        Name = 'Fruit_Logic_pickup_02',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Fruit_Logic_pickup_02',
        Info = '拿起的交互声音'
    },
    [25] = {
        ID = 25,
        Type = 'SoundEffect',
        Name = 'Weapon_Common_pickup',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Weapon_Common_pickup',
        Info = '装备的交互声音'
    },
    [26] = {
        ID = 26,
        Type = 'SoundEffect',
        Name = 'Fruit_Logic_eat&boost',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Fruit_Logic_eat&boost',
        Info = '吃食物的交互声音'
    },
    [27] = {
        ID = 27,
        Type = 'SoundEffect',
        Name = 'Weapon_attack',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Weapon_attack',
        Info = '挥动近战武器（重）'
    },
    [28] = {
        ID = 28,
        Type = 'SoundEffect',
        Name = 'Weapon_LightSaber_attack',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Weapon_LightSaber_attack',
        Info = '挥动光剑'
    },
    [29] = {
        ID = 29,
        Type = 'SoundEffect',
        Name = 'Weapon_knife_attack',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Weapon_knife_attack',
        Info = '挥动近战武器（利刃）'
    },
    [30] = {
        ID = 30,
        Type = 'SoundEffect',
        Name = 'Weapon_Light',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Weapon_Light',
        Info = '挥动近战武器（轻）'
    },
    [31] = {
        ID = 31,
        Type = 'SoundEffect',
        Name = 'Weapon_LightSaber_hit',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Weapon_LightSaber_hit',
        Info = '光剑命中'
    },
    [32] = {
        ID = 32,
        Type = 'SoundEffect',
        Name = 'Weapon_Umbrella_hit',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Weapon_Umbrella_hit',
        Info = '命中玩家'
    },
    [33] = {
        ID = 33,
        Type = 'SoundEffect',
        Name = 'Weapon_Trombone_hit',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Weapon_Trombone_hit',
        Info = '命中除了树、人、动物外其他物体'
    },
    [34] = {
        ID = 34,
        Type = 'SoundEffect',
        Name = 'Item_unequip',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Item_unequip',
        Info = '实体和道具消失时烟雾炸开的声音'
    },
    [35] = {
        ID = 35,
        Type = 'SoundEffect',
        Name = 'Weapon_LightSaber_pickup',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Weapon_LightSaber_pickup',
        Info = '装备光剑'
    },
    [36] = {
        ID = 36,
        Type = 'SoundEffect',
        Name = 'Throw',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Throw',
        Info = '投掷'
    },
    [37] = {
        ID = 37,
        Type = 'SoundEffect',
        Name = 'Weapon_Sword_Hit_Wood_Dull_01',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Weapon_Sword_Hit_Wood_Dull_01',
        Info = '金属命中其他物体'
    },
    [38] = {
        ID = 38,
        Type = 'SoundEffect',
        Name = 'FlyBoardController_ScoreBreaker',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/FlyBoardController_ScoreBreaker',
        Info = '第一名到达终点'
    },
    [39] = {
        ID = 39,
        Type = 'SoundEffect',
        Name = 'Drone_attack_firework_shoot',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Drone_attack_firework_shoot',
        Info = '第二名到达终点'
    },
    [40] = {
        ID = 40,
        Type = 'SoundEffect',
        Name = '',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/',
        Info = '第三名到达终点'
    },
    [41] = {
        ID = 41,
        Type = 'SoundEffect',
        Name = '',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/',
        Info = '第四名到达终点'
    },
    [42] = {
        ID = 42,
        Type = 'SoundEffect',
        Name = 'Clip_Lock',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Clip_Lock',
        Info = '放夹子'
    },
    [43] = {
        ID = 43,
        Type = 'SoundEffect',
        Name = 'Clip_Release',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Clip_Release',
        Info = '夹中动物'
    },
    [44] = {
        ID = 44,
        Type = 'SoundEffect',
        Name = 'Clip_Destory',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Clip_Destory',
        Info = '夹子被毁坏'
    },
    [45] = {
        ID = 45,
        Type = 'SoundEffect',
        Name = 'Deer_Hurt',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Deer_Hurt',
        Info = '鹿受击'
    },
    [46] = {
        ID = 46,
        Type = 'SoundEffect',
        Name = 'Deer_Dead',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Deer_Dead',
        Info = '鹿死亡'
    },
    [47] = {
        ID = 47,
        Type = 'SoundEffect',
        Name = 'Bird',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Bird',
        Info = '山鸡受击'
    },
    [48] = {
        ID = 48,
        Type = 'SoundEffect',
        Name = 'Bird',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Bird',
        Info = '山鸡死亡'
    },
    [49] = {
        ID = 49,
        Type = 'SoundEffect',
        Name = 'Pig_Hurt',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Pig_Hurt',
        Info = '野猪受击'
    },
    [50] = {
        ID = 50,
        Type = 'SoundEffect',
        Name = 'Pig_Dead',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Pig_Dead',
        Info = '野鸡死亡'
    },
    [51] = {
        ID = 51,
        Type = 'SoundEffect',
        Name = 'Wolf_Hurt',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Wolf_Hurt',
        Info = '狼受击'
    },
    [52] = {
        ID = 52,
        Type = 'SoundEffect',
        Name = 'Wolf_Dead',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Wolf_Dead',
        Info = '狼死亡'
    },
    [53] = {
        ID = 53,
        Type = 'SoundEffect',
        Name = 'Bird',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Bird',
        Info = '猫头鹰受击'
    },
    [54] = {
        ID = 54,
        Type = 'SoundEffect',
        Name = 'Bird',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Bird',
        Info = '猫头鹰死亡'
    },
    [55] = {
        ID = 55,
        Type = 'SoundEffect',
        Name = 'Weapon_Bow_draw',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Weapon_Bow_draw',
        Info = '拉弓'
    },
    [56] = {
        ID = 56,
        Type = 'SoundEffect',
        Name = 'Weapon_Bow_shoot',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Weapon_Bow_shoot',
        Info = '放箭'
    },
    [57] = {
        ID = 57,
        Type = 'SoundEffect',
        Name = 'Bear_Hurt',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Bear_Hurt',
        Info = '熊受击'
    },
    [58] = {
        ID = 58,
        Type = 'SoundEffect',
        Name = 'bear_pain_hurt_groan_01',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/bear_pain_hurt_groan_01',
        Info = '熊死亡'
    },
    [59] = {
        ID = 59,
        Type = 'SoundEffect',
        Name = 'Rocket_Launcher',
        IsLoop = true,
        Volume = 60.0,
        Path = 'Audio/Rocket_Launcher',
        Info = '弹射椅发射的音效'
    },
    [60] = {
        ID = 60,
        Type = 'SoundEffect',
        Name = '',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/',
        Info = '弹射椅故障旋转的音效'
    },
    [61] = {
        ID = 61,
        Type = 'SoundEffect',
        Name = '',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/',
        Info = '玩家失败落下时的音效'
    },
    [62] = {
        ID = 62,
        Type = 'SoundEffect',
        Name = '',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/',
        Info = '喷气椅机械音'
    },
    [63] = {
        ID = 63,
        Type = 'SoundEffect',
        Name = 'Sfx_ChangeStatu_5s_SlotMachine',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/Sfx_ChangeStatu_5s_SlotMachine',
        Info = '猜拳倒计时'
    },
    [64] = {
        ID = 64,
        Type = 'SoundEffect',
        Name = '',
        IsLoop = true,
        Volume = 60.0,
        Path = 'Audio/',
        Info = '营地里和飞碟里BGM'
    },
    [65] = {
        ID = 65,
        Type = 'SoundEffect',
        Name = 'TempBGM',
        IsLoop = true,
        Volume = 60.0,
        Path = 'Audio/TempBGM',
        Info = '野外探索狩猎时BGM'
    },
    [66] = {
        ID = 66,
        Type = 'SoundEffect',
        Name = '',
        IsLoop = true,
        Volume = 60.0,
        Path = 'Audio/',
        Info = '迷宫内BGM'
    },
    [67] = {
        ID = 67,
        Type = 'SoundEffect',
        Name = 'E3',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/E3',
        Info = '吉他音'
    },
    [68] = {
        ID = 68,
        Type = 'SoundEffect',
        Name = 'F3',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/F3',
        Info = ''
    },
    [69] = {
        ID = 69,
        Type = 'SoundEffect',
        Name = 'F#3',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/F#3',
        Info = ''
    },
    [70] = {
        ID = 70,
        Type = 'SoundEffect',
        Name = 'G3',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/G3',
        Info = ''
    },
    [71] = {
        ID = 71,
        Type = 'SoundEffect',
        Name = 'G#3',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/G#3',
        Info = ''
    },
    [72] = {
        ID = 72,
        Type = 'SoundEffect',
        Name = 'A3',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/A3',
        Info = ''
    },
    [73] = {
        ID = 73,
        Type = 'SoundEffect',
        Name = 'A#3',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/A#3',
        Info = ''
    },
    [74] = {
        ID = 74,
        Type = 'SoundEffect',
        Name = 'B3',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/B3',
        Info = ''
    },
    [75] = {
        ID = 75,
        Type = 'SoundEffect',
        Name = 'C4',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/C4',
        Info = ''
    },
    [76] = {
        ID = 76,
        Type = 'SoundEffect',
        Name = 'C#4',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/C#4',
        Info = ''
    },
    [77] = {
        ID = 77,
        Type = 'SoundEffect',
        Name = 'D4',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/D4',
        Info = ''
    },
    [78] = {
        ID = 78,
        Type = 'SoundEffect',
        Name = 'D#4',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/D#4',
        Info = ''
    },
    [79] = {
        ID = 79,
        Type = 'SoundEffect',
        Name = 'E4',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/E4',
        Info = ''
    },
    [80] = {
        ID = 80,
        Type = 'SoundEffect',
        Name = 'F4',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/F4',
        Info = ''
    },
    [81] = {
        ID = 81,
        Type = 'SoundEffect',
        Name = 'F#4',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/F#4',
        Info = ''
    },
    [82] = {
        ID = 82,
        Type = 'SoundEffect',
        Name = 'G4',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/G4',
        Info = ''
    },
    [83] = {
        ID = 83,
        Type = 'SoundEffect',
        Name = 'G#4',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/G#4',
        Info = ''
    },
    [84] = {
        ID = 84,
        Type = 'SoundEffect',
        Name = 'A4',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/A4',
        Info = ''
    },
    [85] = {
        ID = 85,
        Type = 'SoundEffect',
        Name = 'A#4',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/A#4',
        Info = ''
    },
    [86] = {
        ID = 86,
        Type = 'SoundEffect',
        Name = 'B4',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/B4',
        Info = ''
    },
    [87] = {
        ID = 87,
        Type = 'SoundEffect',
        Name = 'C5',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/C5',
        Info = ''
    },
    [88] = {
        ID = 88,
        Type = 'SoundEffect',
        Name = 'C#5',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/C#5',
        Info = ''
    },
    [89] = {
        ID = 89,
        Type = 'SoundEffect',
        Name = 'D5',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/D5',
        Info = ''
    },
    [90] = {
        ID = 90,
        Type = 'SoundEffect',
        Name = 'D#5',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/D#5',
        Info = ''
    },
    [91] = {
        ID = 91,
        Type = 'SoundEffect',
        Name = 'E5',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/E5',
        Info = ''
    },
    [92] = {
        ID = 92,
        Type = 'SoundEffect',
        Name = 'F5',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/F5',
        Info = ''
    },
    [93] = {
        ID = 93,
        Type = 'SoundEffect',
        Name = 'F#5',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/F#5',
        Info = ''
    },
    [94] = {
        ID = 94,
        Type = 'SoundEffect',
        Name = 'G5',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/G5',
        Info = ''
    },
    [95] = {
        ID = 95,
        Type = 'SoundEffect',
        Name = 'G#5',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/G#5',
        Info = ''
    },
    [96] = {
        ID = 96,
        Type = 'SoundEffect',
        Name = 'A5',
        IsLoop = false,
        Volume = 60.0,
        Path = 'Audio/A5',
        Info = ''
    }
}

return SoundXls
