--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: .//PlayerActState.xlsx

local PlayerActStateXls = {
    [1] = {
        ID = 1,
        Name = 'Idle',
        NextName = 'Idle',
        Dur = 0.0
    },
    [2] = {
        ID = 2,
        Name = 'Walk',
        NextName = 'Walk',
        Dur = 0.0
    },
    [3] = {
        ID = 3,
        Name = 'Run',
        NextName = 'Run',
        Dur = 0.0
    },
    [4] = {
        ID = 4,
        Name = 'Jump',
        NextName = 'Idle',
        Dur = 0.6
    },
    [5] = {
        ID = 5,
        Name = 'Vertigo',
        NextName = 'Idle',
        Dur = 2.0
    },
    [6] = {
        ID = 6,
        Name = 'Fly',
        NextName = 'Fly',
        Dur = 0.0
    },
    [7] = {
        ID = 7,
        Name = 'Hit',
        NextName = 'Idle',
        Dur = 0.2
    },
    [8] = {
        ID = 8,
        Name = 'SwimIdle',
        NextName = 'SwimIdle',
        Dur = 0.0
    },
    [9] = {
        ID = 9,
        Name = 'Swimming',
        NextName = 'Swimming',
        Dur = 0.0
    },
    [10] = {
        ID = 10,
        Name = 'TakeOutItem',
        NextName = 'TakeOutItem',
        Dur = 0.0
    },
    [11] = {
        ID = 11,
        Name = 'UseItem',
        NextName = 'UseItem',
        Dur = 0.0
    },
    [12] = {
        ID = 12,
        Name = 'BowIdle',
        NextName = 'BowIdle',
        Dur = 0.0
    },
    [13] = {
        ID = 13,
        Name = 'BowWalk',
        NextName = 'BowWalk',
        Dur = 0.0
    },
    [14] = {
        ID = 14,
        Name = 'BowRun',
        NextName = 'BowRun',
        Dur = 0.0
    },
    [15] = {
        ID = 15,
        Name = 'BowJump',
        NextName = 'BowIdle',
        Dur = 0.6
    },
    [16] = {
        ID = 16,
        Name = 'BowChargeIdle',
        NextName = 'BowChargeIdle',
        Dur = 0.0
    },
    [17] = {
        ID = 17,
        Name = 'BowAttack',
        NextName = 'BowIdle',
        Dur = 0.35
    },
    [18] = {
        ID = 18,
        Name = 'BowHit',
        NextName = 'BowIdle',
        Dur = 0.2
    },
    [19] = {
        ID = 19,
        Name = 'PistolIdle',
        NextName = 'PistolIdle',
        Dur = 0.0
    },
    [20] = {
        ID = 20,
        Name = 'PistolRun',
        NextName = 'PistolRun',
        Dur = 0.0
    },
    [21] = {
        ID = 21,
        Name = 'PistolWalk',
        NextName = 'PistolWalk',
        Dur = 0.0
    },
    [22] = {
        ID = 22,
        Name = 'PistolJump',
        NextName = 'PistolIdle',
        Dur = 0.6
    },
    [23] = {
        ID = 23,
        Name = 'PistolAttack',
        NextName = 'PistolIdle',
        Dur = 0.2
    },
    [24] = {
        ID = 24,
        Name = 'PistolHit',
        NextName = 'PistolIdle',
        Dur = 0.2
    }
}

return PlayerActStateXls
