--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//GameLotus.xlsx

local LotusInfoXls = {
    [1] = {
        Id = 1,
        Type = 1,
        Modle = 'heye_01',
        LifeTime = -1.0,
        AniSpeed = 1.0
    },
    [2] = {
        Id = 2,
        Type = 2,
        Modle = 'heye_02',
        LifeTime = 7.0,
        AniSpeed = 1.0
    },
    [3] = {
        Id = 3,
        Type = 2,
        Modle = 'heye_02',
        LifeTime = 5.0,
        AniSpeed = 1.0
    },
    [4] = {
        Id = 4,
        Type = 2,
        Modle = 'heye_02',
        LifeTime = 3.0,
        AniSpeed = 1.0
    },
    [5] = {
        Id = 5,
        Type = 3,
        Modle = 'heye_03',
        LifeTime = 0.5,
        AniSpeed = 3.0
    }
}

return LotusInfoXls
