--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: .//PeriodCoin.xlsx

local PeriodCoinXls = {
    [1] = {
        [1] = {
            Fid = 1,
            Pid = 1,
            Pos = Vector3(74.915634, 2.580454, 20.371872),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 5
        },
        [2] = {
            Fid = 1,
            Pid = 2,
            Pos = Vector3(33.326153, -11.240738, 20.306084),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 5
        },
        [3] = {
            Fid = 1,
            Pid = 3,
            Pos = Vector3(67.916039, -0.884123, 26.424288),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 5
        },
        [4] = {
            Fid = 1,
            Pid = 4,
            Pos = Vector3(41.773041, -2.821258, 41.738747),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 5
        },
        [5] = {
            Fid = 1,
            Pid = 5,
            Pos = Vector3(50.923164, -4.263489, 31.364449),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 5
        },
        [6] = {
            Fid = 1,
            Pid = 6,
            Pos = Vector3(86.431480, 5.445843, 6.654531),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 5
        },
        [7] = {
            Fid = 1,
            Pid = 7,
            Pos = Vector3(87.031624, 3.817593, 15.022520),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 5
        },
        [8] = {
            Fid = 1,
            Pid = 8,
            Pos = Vector3(92.245323, 6.261104, 5.794095),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 5
        },
        [9] = {
            Fid = 1,
            Pid = 9,
            Pos = Vector3(94.446808, 1.857781, 0.976482),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 5
        },
        [10] = {
            Fid = 1,
            Pid = 10,
            Pos = Vector3(104.062538, 0.390348, -0.094970),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 5
        },
        [11] = {
            Fid = 1,
            Pid = 11,
            Pos = Vector3(117.619705, 0.390348, -1.272205),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 5
        },
        [12] = {
            Fid = 1,
            Pid = 12,
            Pos = Vector3(108.024521, -1.121371, 1.728619),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 5
        },
        [13] = {
            Fid = 1,
            Pid = 13,
            Pos = Vector3(109.842949, -1.678864, 7.723686),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 5
        },
        [14] = {
            Fid = 1,
            Pid = 14,
            Pos = Vector3(108.808334, 0.174450, 23.158825),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 5
        },
        [15] = {
            Fid = 1,
            Pid = 15,
            Pos = Vector3(102.859222, -0.330254, 28.751358),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 5
        },
        [16] = {
            Fid = 1,
            Pid = 16,
            Pos = Vector3(96.377281, -13.394413, -2.742851),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 5
        },
        [17] = {
            Fid = 1,
            Pid = 17,
            Pos = Vector3(111.855721, -11.858931, 1.103946),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 5
        },
        [18] = {
            Fid = 1,
            Pid = 18,
            Pos = Vector3(119.797791, -11.858931, 6.629025),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 5
        },
        [19] = {
            Fid = 1,
            Pid = 19,
            Pos = Vector3(118.469055, -11.858931, 27.595881),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 5
        },
        [20] = {
            Fid = 1,
            Pid = 20,
            Pos = Vector3(98.371643, 2.498068, -3.443573),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 5
        },
        [21] = {
            Fid = 1,
            Pid = 21,
            Pos = Vector3(77.111618, 9.729330, 13.990946),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 5
        },
        [22] = {
            Fid = 1,
            Pid = 22,
            Pos = Vector3(113.689781, -7.341907, 18.366402),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 5
        },
        [23] = {
            Fid = 1,
            Pid = 23,
            Pos = Vector3(109.013725, -10.108538, 30.050188),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 5
        },
        [24] = {
            Fid = 1,
            Pid = 24,
            Pos = Vector3(103.228912, -6.612459, -5.170008),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 5
        },
        [25] = {
            Fid = 1,
            Pid = 25,
            Pos = Vector3(94.366653, 6.261104, 9.657903),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 2
        },
        [26] = {
            Fid = 1,
            Pid = 26,
            Pos = Vector3(126.199936, 8.288073, -19.070547),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 1
        }
    },
    [4] = {
        [1] = {
            Fid = 4,
            Pid = 1,
            Pos = Vector3(-75.995804, 75.707085, -10.714348),
            Rot = EulerDegree(0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 8
        },
        [2] = {
            Fid = 4,
            Pid = 2,
            Pos = Vector3(-94.295120, 74.039223, -15.766949),
            Rot = EulerDegree(0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 8
        },
        [3] = {
            Fid = 4,
            Pid = 3,
            Pos = Vector3(-85.058029, 75.866356, -30.108248),
            Rot = EulerDegree(0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 8
        },
        [4] = {
            Fid = 4,
            Pid = 4,
            Pos = Vector3(-61.725952, 75.707085, -14.371435),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 8
        },
        [5] = {
            Fid = 4,
            Pid = 5,
            Pos = Vector3(-86.617989, 73.975868, -11.200914),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 8
        },
        [6] = {
            Fid = 4,
            Pid = 6,
            Pos = Vector3(-122.352135, 65.989723, 17.271353),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 8
        },
        [7] = {
            Fid = 4,
            Pid = 7,
            Pos = Vector3(-89.902306, 72.177177, 79.121078),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 8
        },
        [8] = {
            Fid = 4,
            Pid = 8,
            Pos = Vector3(-86.562134, 75.866356, -21.947836),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 8
        },
        [9] = {
            Fid = 4,
            Pid = 9,
            Pos = Vector3(-92.230850, 75.781837, -27.170578),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 8
        },
        [10] = {
            Fid = 4,
            Pid = 10,
            Pos = Vector3(-71.991333, 74.457436, -15.146814),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 8
        },
        [11] = {
            Fid = 4,
            Pid = 11,
            Pos = Vector3(-95.975334, 71.300926, 66.048798),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 8
        },
        [12] = {
            Fid = 4,
            Pid = 12,
            Pos = Vector3(-93.055618, 72.566238, 70.994698),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 8
        },
        [13] = {
            Fid = 4,
            Pid = 13,
            Pos = Vector3(-123.257614, 66.562798, 21.947720),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 8
        },
        [14] = {
            Fid = 4,
            Pid = 14,
            Pos = Vector3(-90.151733, 72.674492, 73.450691),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 8
        },
        [15] = {
            Fid = 4,
            Pid = 15,
            Pos = Vector3(-124.071983, 65.685333, 30.068110),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 8
        },
        [16] = {
            Fid = 4,
            Pid = 16,
            Pos = Vector3(-91.922539, 72.963898, 76.028976),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 8
        },
        [17] = {
            Fid = 4,
            Pid = 17,
            Pos = Vector3(-126.018311, 66.673218, 19.658134),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 8
        },
        [18] = {
            Fid = 4,
            Pid = 18,
            Pos = Vector3(-123.002930, 67.011017, 26.733995),
            Rot = EulerDegree(0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 8
        },
        [19] = {
            Fid = 4,
            Pid = 19,
            Pos = Vector3(-174.361862, -0.272245, 28.211317),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 8
        }
    },
    [5] = {
        [1] = {
            Fid = 5,
            Pid = 1,
            Pos = Vector3(-158.747757, -9.839782, 80.649750),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 4
        },
        [2] = {
            Fid = 5,
            Pid = 2,
            Pos = Vector3(-50.438534, 11.487173, 102.109352),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 4
        },
        [3] = {
            Fid = 5,
            Pid = 3,
            Pos = Vector3(-16.314404, 22.338280, 114.121002),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 4
        },
        [4] = {
            Fid = 5,
            Pid = 4,
            Pos = Vector3(-71.511200, -13.277767, 35.110680),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 4
        },
        [5] = {
            Fid = 5,
            Pid = 5,
            Pos = Vector3(-92.142342, 13.476738, 100.198692),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 4
        },
        [6] = {
            Fid = 5,
            Pid = 6,
            Pos = Vector3(-41.650955, -11.374971, 61.922855),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 4
        },
        [7] = {
            Fid = 5,
            Pid = 7,
            Pos = Vector3(-33.549911, -10.197646, 71.607407),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 4
        },
        [8] = {
            Fid = 5,
            Pid = 8,
            Pos = Vector3(-170.068283, 1.890959, 129.027512),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 4
        },
        [9] = {
            Fid = 5,
            Pid = 9,
            Pos = Vector3(-67.071266, 1.890959, -67.892540),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 4
        },
        [10] = {
            Fid = 5,
            Pid = 10,
            Pos = Vector3(14.593680, -7.350087, -14.253241),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 4
        },
        [11] = {
            Fid = 5,
            Pid = 11,
            Pos = Vector3(-94.316284, -7.475637, 67.543129),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 4
        },
        [12] = {
            Fid = 5,
            Pid = 12,
            Pos = Vector3(-120.996834, -13.666782, 40.716202),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 4
        },
        [13] = {
            Fid = 5,
            Pid = 13,
            Pos = Vector3(-141.380661, -0.364467, 34.703995),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 4
        },
        [14] = {
            Fid = 5,
            Pid = 14,
            Pos = Vector3(-100.896606, -4.275764, -27.357367),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 4
        },
        [15] = {
            Fid = 5,
            Pid = 15,
            Pos = Vector3(-65.991493, -5.738024, -27.696426),
            Rot = EulerDegree(-0.000000, 16.500000, 0.000000),
            CoinType = 'Random',
            Num = 4
        },
        [16] = {
            Fid = 5,
            Pid = 16,
            Pos = Vector3(-53.598759, -4.942509, -30.008411),
            Rot = EulerDegree(-0.000000, 300.500000, 0.000000),
            CoinType = 'Random',
            Num = 4
        },
        [17] = {
            Fid = 5,
            Pid = 17,
            Pos = Vector3(-31.637678, -8.492792, -32.477882),
            Rot = EulerDegree(-0.000000, -59.499973, -0.000000),
            CoinType = 'Random',
            Num = 4
        },
        [18] = {
            Fid = 5,
            Pid = 18,
            Pos = Vector3(-27.037695, -13.670100, 7.896946),
            Rot = EulerDegree(-0.000000, -59.499973, -0.000000),
            CoinType = 'Random',
            Num = 4
        },
        [19] = {
            Fid = 5,
            Pid = 19,
            Pos = Vector3(-160.642502, 1.360978, 33.000542),
            Rot = EulerDegree(-0.000000, -59.499973, -0.000000),
            CoinType = 'Random',
            Num = 4
        }
    },
    [6] = {
        [1] = {
            Fid = 6,
            Pid = 1,
            Pos = Vector3(-4.254529, -11.977487, 70.578964),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 1
        },
        [2] = {
            Fid = 6,
            Pid = 2,
            Pos = Vector3(-12.861933, -11.977487, 78.591591),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 1
        },
        [3] = {
            Fid = 6,
            Pid = 3,
            Pos = Vector3(-21.551977, -11.977487, 72.823395),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 1
        },
        [4] = {
            Fid = 6,
            Pid = 4,
            Pos = Vector3(-26.354151, -11.977487, 68.834404),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 1
        },
        [5] = {
            Fid = 6,
            Pid = 5,
            Pos = Vector3(-17.370836, -11.977487, 68.565910),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 1
        },
        [6] = {
            Fid = 6,
            Pid = 6,
            Pos = Vector3(-11.538547, -11.977487, 64.458862),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 1
        },
        [7] = {
            Fid = 6,
            Pid = 7,
            Pos = Vector3(3.298235, -11.977487, 65.301636),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 1
        },
        [8] = {
            Fid = 6,
            Pid = 8,
            Pos = Vector3(10.920105, -11.977487, 63.870041),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 1
        },
        [9] = {
            Fid = 6,
            Pid = 9,
            Pos = Vector3(6.549878, -11.977487, 56.317451),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 1
        },
        [10] = {
            Fid = 6,
            Pid = 10,
            Pos = Vector3(2.599062, -11.977487, 49.431786),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 1
        },
        [11] = {
            Fid = 6,
            Pid = 11,
            Pos = Vector3(-4.589310, -11.977487, 55.711395),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 1
        },
        [12] = {
            Fid = 6,
            Pid = 12,
            Pos = Vector3(-12.152050, -11.977487, 55.878799),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 1
        },
        [13] = {
            Fid = 6,
            Pid = 13,
            Pos = Vector3(-27.026766, -11.977487, 57.024117),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 1
        },
        [14] = {
            Fid = 6,
            Pid = 14,
            Pos = Vector3(-22.519972, -11.977487, 62.424625),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 1
        },
        [15] = {
            Fid = 6,
            Pid = 15,
            Pos = Vector3(-20.187588, -11.977487, 53.478458),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 1
        },
        [16] = {
            Fid = 6,
            Pid = 16,
            Pos = Vector3(-33.060844, -11.977487, 53.225269),
            Rot = EulerDegree(0.000000, 0.000000, 0.000000),
            CoinType = 'Random',
            Num = 1
        }
    }
}

return PeriodCoinXls
