--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//Item.xlsm

local TaskItemXls = {
    [5001] = {
        ItemID = 5001,
        Npc = {1},
        RewardItem = 5002,
        RewardGold = 0,
        NpcText = 'TaskItem_NpcText_5001'
    },
    [5002] = {
        ItemID = 5002,
        Npc = {2},
        RewardItem = nil,
        RewardGold = 0,
        NpcText = 'TaskItem_NpcText_5002'
    }
}

return TaskItemXls
