--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see https://www.projectdavinci.com/
--- @see https://github.com/endaye/avatar-ava-xls2lua
--- source file: .//Item.xlsm

local WeaponItemXls = {
    [1001] = {
        ItemID = 1001,
        Model = 'M_Sword',
        AnimUse = 'TwoHandedSwordAttack1',
        UseCD = 0.5,
        AttckCD = '2.0',
        SellGold = 3,
        AnimState = 1,
        Offset = Vector3(0, 0, 0),
        Angle = EulerDegree(0, 0, 0),
        Range = 0.0,
        HealthChange = 34,
        HitAddBuff = nil,
        HitRemoveBuff = nil,
        HitEffect = '',
        HitAnim = '',
        UseSound = '',
        HitSound = ''
    }
}

return WeaponItemXls
